export type Algorithm = {
  slug: string;
  name: string;
  year: string;
  inventor: string;
  category: "factoring" | "search" | "simulation" | "optimization" | "machine-learning" | "cryptography" | "foundational";
  speedupType: "exponential" | "quadratic" | "polynomial" | "heuristic" | "none-proven";
  difficulty: 1 | 2 | 3 | 4 | 5;
  summary: string;
  problem: string;
  howItWorks: string;
  realWorldImpact: string;
  relatedLearnSlug?: string;
};

export const algorithms: Algorithm[] = [
  {
    slug: "shors-algorithm",
    name: "Shor's Algorithm",
    year: "1994",
    inventor: "Peter Shor",
    category: "factoring",
    speedupType: "exponential",
    difficulty: 4,
    summary: "Factors large numbers exponentially faster than any known classical algorithm, threatening RSA encryption.",
    problem: "Finding the prime factors of a large composite number — believed to be intractable for classical computers at scale.",
    howItWorks: "Transforms factoring into a period-finding problem, solved efficiently using the Quantum Fourier Transform, then recovers factors via classical post-processing.",
    realWorldImpact: "Directly motivates post-quantum cryptography; would break RSA and similar encryption if run on a large enough fault-tolerant quantum computer.",
    relatedLearnSlug: "shors-algorithm",
  },
  {
    slug: "grovers-algorithm",
    name: "Grover's Algorithm",
    year: "1996",
    inventor: "Lov Grover",
    category: "search",
    speedupType: "quadratic",
    difficulty: 3,
    summary: "Searches unsorted data in roughly √N steps instead of N, using amplitude amplification.",
    problem: "Finding a specific item in an unsorted list or database without any shortcut like sorting.",
    howItWorks: "Repeatedly applies an oracle that marks the correct answer, then amplifies its probability through reflection operations, concentrating probability onto the right answer.",
    realWorldImpact: "Broadly applicable to search and optimization problems; also halves the effective key strength of certain symmetric encryption schemes.",
    relatedLearnSlug: "grovers-algorithm",
  },
  {
    slug: "deutsch-jozsa",
    name: "Deutsch-Jozsa Algorithm",
    year: "1992",
    inventor: "David Deutsch & Richard Jozsa",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 3,
    summary: "The first algorithm to prove a quantum computer could solve a problem exponentially faster than any classical deterministic algorithm.",
    problem: "Determining whether a given function is 'constant' (same output for all inputs) or 'balanced' (different outputs for half the inputs).",
    howItWorks: "Uses superposition to evaluate the function on all inputs simultaneously, then uses interference so a single measurement reveals whether the function is constant or balanced.",
    realWorldImpact: "Mainly historical and educational — it proved quantum speedup was possible in principle, paving the way for Shor's and Grover's algorithms, though the problem itself has limited practical use.",
  },
  {
    slug: "simons-algorithm",
    name: "Simon's Algorithm",
    year: "1994",
    inventor: "Daniel Simon",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 4,
    summary: "Finds a hidden pattern (period) in a function exponentially faster than classical methods, directly inspiring Shor's Algorithm.",
    problem: "Given a function with a hidden 'XOR-periodicity,' find the hidden period.",
    howItWorks: "Uses superposition and the structure of the problem to extract the hidden period using only a linear number of quantum queries, versus an exponential number classically.",
    realWorldImpact: "Primarily of theoretical importance — Simon's problem directly inspired Peter Shor's approach to factoring, making it a key stepping stone in quantum algorithm history.",
  },
  {
    slug: "quantum-fourier-transform",
    name: "Quantum Fourier Transform (QFT)",
    year: "1994",
    inventor: "Don Coppersmith (building on classical FFT)",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 4,
    summary: "The quantum analog of the discrete Fourier transform, performed exponentially faster than the classical Fast Fourier Transform.",
    problem: "Transforming a quantum state to reveal its underlying periodicity or frequency structure.",
    howItWorks: "Uses a sequence of Hadamard and controlled-phase gates to transform amplitudes, extracting frequency information encoded across a register of qubits.",
    realWorldImpact: "A core subroutine used inside Shor's Algorithm and quantum phase estimation; rarely used as a standalone algorithm but essential as a building block.",
  },
  {
    slug: "quantum-phase-estimation",
    name: "Quantum Phase Estimation (QPE)",
    year: "1995",
    inventor: "Alexei Kitaev",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 4,
    summary: "Estimates the eigenvalue (phase) associated with a quantum operation, a critical building block for many other quantum algorithms.",
    problem: "Determining the precise phase associated with an eigenstate of a unitary quantum operation.",
    howItWorks: "Combines controlled application of the unitary operation with the inverse Quantum Fourier Transform to extract the phase to high precision.",
    realWorldImpact: "Used inside Shor's Algorithm, quantum chemistry simulations, and the HHL algorithm for solving linear systems — a true workhorse subroutine.",
  },
  {
    slug: "vqe",
    name: "Variational Quantum Eigensolver (VQE)",
    year: "2014",
    inventor: "Peruzzo et al.",
    category: "simulation",
    speedupType: "heuristic",
    difficulty: 3,
    summary: "A hybrid quantum-classical algorithm for finding the lowest energy state of a molecule or material, designed to work on noisy near-term hardware.",
    problem: "Finding the ground-state energy of a quantum system (like a molecule), which is exponentially hard to compute classically as system size grows.",
    howItWorks: "A quantum computer prepares trial states and measures their energy, while a classical optimizer iteratively adjusts parameters to minimize that energy — splitting the work between quantum and classical hardware.",
    realWorldImpact: "One of the most promising NISQ-era applications, actively used in early quantum chemistry and materials science research, including drug discovery exploration.",
    relatedLearnSlug: "quantum-algorithms",
  },
  {
    slug: "qaoa",
    name: "Quantum Approximate Optimization Algorithm (QAOA)",
    year: "2014",
    inventor: "Farhi, Goldstone & Gutmann",
    category: "optimization",
    speedupType: "heuristic",
    difficulty: 3,
    summary: "A hybrid algorithm for finding approximate solutions to combinatorial optimization problems on near-term quantum hardware.",
    problem: "Approximately solving optimization problems like Max-Cut, scheduling, or routing — problems with many possible solutions and no easy way to find the best one.",
    howItWorks: "Alternates between quantum operations that explore the solution space and classical optimization that tunes parameters, gradually converging on better solutions.",
    realWorldImpact: "Explored for portfolio optimization, logistics routing, and scheduling problems; whether it offers genuine advantage over the best classical heuristics remains an active research question.",
  },
  {
    slug: "hhl-algorithm",
    name: "HHL Algorithm",
    year: "2009",
    inventor: "Harrow, Hassidim & Lloyd",
    category: "machine-learning",
    speedupType: "exponential",
    difficulty: 5,
    summary: "Solves systems of linear equations exponentially faster than classical methods, under specific conditions.",
    problem: "Solving a system of linear equations (Ax = b) — a problem underlying enormous amounts of scientific computing and machine learning.",
    howItWorks: "Encodes the linear system into a quantum state, uses quantum phase estimation to find eigenvalues, and inverts them to construct the solution — all without ever writing out the full solution vector classically.",
    realWorldImpact: "Has significant caveats (requires the matrix to be 'sparse' and well-conditioned, and the output is a quantum state, not a classical answer), but is foundational to quantum machine learning research.",
  },
  {
    slug: "quantum-walk-search",
    name: "Quantum Walk Algorithms",
    year: "2003 (Childs et al.)",
    inventor: "Multiple contributors",
    category: "search",
    speedupType: "polynomial",
    difficulty: 4,
    summary: "The quantum analog of a classical random walk, used to search graphs and networks faster than classical methods in specific structured cases.",
    problem: "Searching or traversing a large graph or network structure to find a target node or path.",
    howItWorks: "Exploits quantum superposition and interference to spread probability across a graph differently than a classical random walk, in some cases reaching target nodes quadratically faster.",
    realWorldImpact: "Used in specialized search applications and as a building block for some optimization and machine learning algorithms; less broadly known than Grover's but mathematically related.",
  },
  {
    slug: "quantum-counting",
    name: "Quantum Counting",
    year: "1998",
    inventor: "Brassard, Høyer & Tapp",
    category: "search",
    speedupType: "quadratic",
    difficulty: 3,
    summary: "Estimates the number of solutions to a search problem, combining Grover's Algorithm with quantum phase estimation.",
    problem: "Determining how many items in a dataset satisfy a given condition, without checking every item individually.",
    howItWorks: "Uses the structure of Grover's amplitude amplification combined with phase estimation to extract a count rather than a single answer.",
    realWorldImpact: "Useful in cryptanalysis and statistical estimation tasks where the quantity of solutions matters as much as finding one example.",
  },
  {
    slug: "quantum-amplitude-estimation",
    name: "Quantum Amplitude Estimation",
    year: "2000",
    inventor: "Brassard, Høyer, Mosca & Tapp",
    category: "optimization",
    speedupType: "quadratic",
    difficulty: 4,
    summary: "Estimates an unknown probability or expected value quadratically faster than classical Monte Carlo sampling.",
    problem: "Estimating the probability of an event or the expected value of a function, traditionally done via repeated random sampling (Monte Carlo methods).",
    howItWorks: "Combines amplitude amplification with phase estimation to extract a probability estimate with quadratically fewer samples than classical Monte Carlo.",
    realWorldImpact: "A leading candidate for near-term financial applications like risk analysis and options pricing, where Monte Carlo methods are already heavily used classically.",
  },
  {
    slug: "quantum-teleportation-protocol",
    name: "Quantum Teleportation Protocol",
    year: "1993",
    inventor: "Bennett, Brassard, Crépeau, Jozsa, Peres & Wootters",
    category: "foundational",
    speedupType: "none-proven",
    difficulty: 3,
    summary: "A protocol for transferring an unknown quantum state from one location to another using entanglement and classical communication.",
    problem: "Moving a fragile, unknown quantum state to a distant location without physically transporting the particle itself.",
    howItWorks: "Uses a pre-shared entangled pair plus a measurement and classical message to reconstruct the original quantum state at the destination, destroying the original in the process (consistent with the no-cloning theorem).",
    realWorldImpact: "Foundational to quantum networking and the long-term vision of a quantum internet; experimentally demonstrated over increasing distances, including via satellite.",
  },
  {
    slug: "bb84-protocol",
    name: "BB84 Quantum Key Distribution",
    year: "1984",
    inventor: "Bennett & Brassard",
    category: "cryptography",
    speedupType: "none-proven",
    difficulty: 2,
    summary: "The first quantum key distribution protocol, allowing two parties to generate a shared secret key with security guaranteed by physics rather than mathematical assumptions.",
    problem: "Establishing a shared secret encryption key between two parties in a way that reveals any eavesdropping attempt.",
    howItWorks: "Encodes key bits in the polarization of single photons; any attempt to intercept and measure them disturbs the quantum state in a detectable way, revealing eavesdropping.",
    realWorldImpact: "Commercially deployed today in specific high-security contexts (banking, government); the conceptual foundation for all quantum cryptography that followed.",
  },
  {
    slug: "e91-protocol",
    name: "E91 Quantum Key Distribution",
    year: "1991",
    inventor: "Artur Ekert",
    category: "cryptography",
    speedupType: "none-proven",
    difficulty: 3,
    summary: "A quantum key distribution protocol based on entangled particle pairs and Bell inequality tests rather than single-photon polarization.",
    problem: "Establishing a shared secret key with security based directly on the foundational properties of quantum entanglement.",
    howItWorks: "Distributes entangled particle pairs to both parties; measuring them in different bases and checking for Bell inequality violations both generates the key and detects eavesdropping.",
    realWorldImpact: "Connects practical cryptography directly to the foundational tests of quantum mechanics (Bell's theorem), and underlies some modern device-independent QKD schemes.",
  },
  {
    slug: "quantum-supremacy-sampling",
    name: "Random Circuit Sampling",
    year: "2019 (Google demonstration)",
    inventor: "Google Quantum AI team",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 4,
    summary: "A computational task used to demonstrate 'quantum supremacy' — sampling outputs from a deliberately complex, randomly generated quantum circuit.",
    problem: "Generating samples from the probability distribution produced by a large random quantum circuit — a task believed exponentially hard to simulate classically.",
    howItWorks: "Runs a circuit of random quantum gates across many qubits, then measures the output, repeating many times to build a statistical sample of the underlying probability distribution.",
    realWorldImpact: "Has no direct practical application — its significance was purely as a benchmark demonstrating quantum hardware capability, and the 'supremacy' claim was later contested by improved classical simulations.",
  },
  {
    slug: "quantum-error-correction-codes",
    name: "Quantum Error-Correcting Codes (Shor Code, Surface Code)",
    year: "1995 (Shor Code) / 2002 (Surface Code popularized)",
    inventor: "Peter Shor; Kitaev and others for surface codes",
    category: "foundational",
    speedupType: "none-proven",
    difficulty: 5,
    summary: "Algorithms and encoding schemes for protecting quantum information from errors by spreading it across multiple physical qubits.",
    problem: "Protecting fragile quantum information from decoherence and gate errors without violating the no-cloning theorem.",
    howItWorks: "Encodes one logical qubit across many physical qubits in an entangled configuration, allowing errors to be detected and corrected via syndrome measurements without directly observing the protected quantum information.",
    realWorldImpact: "The central technology required for fault-tolerant quantum computing at scale; without it, large quantum algorithms like Shor's cannot run reliably on real hardware.",
    relatedLearnSlug: "quantum-error-correction",
  },
  {
    slug: "quantum-pca",
    name: "Quantum Principal Component Analysis",
    year: "2014",
    inventor: "Lloyd, Mohseni & Rebentrost",
    category: "machine-learning",
    speedupType: "exponential",
    difficulty: 5,
    summary: "A quantum algorithm for identifying the dominant patterns (principal components) in data, with potential exponential speedup under specific conditions.",
    problem: "Finding the most significant directions of variation in high-dimensional data — a fundamental task in data analysis and machine learning.",
    howItWorks: "Uses quantum phase estimation on a density matrix representing the data to extract eigenvalues and eigenvectors corresponding to principal components.",
    realWorldImpact: "Largely theoretical at present — requires efficient quantum state preparation from classical data, which remains a significant practical bottleneck (sometimes called the 'input problem').",
  },
  {
    slug: "quantum-annealing",
    name: "Quantum Annealing",
    year: "1989 (theory) / 2011 (first commercial hardware)",
    inventor: "Apolloni, Carlucci & Cerf (theory); D-Wave Systems (hardware)",
    category: "optimization",
    speedupType: "heuristic",
    difficulty: 3,
    summary: "A specialized, non-gate-based quantum computing approach that finds low-energy solutions to optimization problems by gradually evolving a quantum system.",
    problem: "Finding near-optimal solutions to combinatorial optimization problems (like scheduling, routing, or portfolio selection).",
    howItWorks: "Starts qubits in a simple, easily prepared quantum state and slowly evolves the system toward a final configuration encoding the problem, exploiting quantum tunneling to escape local minima that would trap classical methods.",
    realWorldImpact: "Commercially available today via D-Wave's quantum annealers, used in early-stage optimization research, though whether it provides genuine quantum advantage over classical heuristics remains debated.",
  },
  {
    slug: "boson-sampling",
    name: "Boson Sampling",
    year: "2011",
    inventor: "Aaronson & Arkhipov",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 4,
    summary: "A specialized computational task using photons (rather than qubits) believed to be exponentially hard to simulate classically, proposed as a near-term path to demonstrating quantum advantage.",
    problem: "Sampling from the output distribution of identical photons passing through a network of optical components — a task with deep connections to permanent calculations in linear algebra.",
    howItWorks: "Sends single photons into a network of beam splitters and mirrors, then measures where they emerge; the resulting statistics are exponentially hard to compute classically as photon number grows.",
    realWorldImpact: "Demonstrated experimentally at increasing scale (notably China's Jiuzhang photonic experiments); like random circuit sampling, primarily valuable as a quantum advantage benchmark rather than a practical application.",
  },
  {
    slug: "bernstein-vazirani",
    name: "Bernstein-Vazirani Algorithm",
    year: "1992",
    inventor: "Ethan Bernstein & Umesh Vazirani",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 2,
    summary: "Finds a hidden binary string encoded in a function using just one query, versus many queries classically — a simple but illustrative example of quantum parallelism.",
    problem: "Given a 'black box' function that computes the dot product of the input with a hidden secret string, determine the secret string.",
    howItWorks: "Prepares all inputs in superposition, queries the function once, and uses interference so that measuring the resulting state directly reveals the hidden string in a single shot.",
    realWorldImpact: "Mainly an educational stepping-stone algorithm, often taught right after Deutsch-Jozsa, used to build intuition for how quantum parallelism extracts global information about a function efficiently.",
  },
  {
    slug: "quantum-counterfeit-coin",
    name: "Quantum Counterfeit Coin Detection",
    year: "2010",
    inventor: "Iwama, Nishimura, Raymond & Teruyama",
    category: "search",
    speedupType: "quadratic",
    difficulty: 3,
    summary: "A quantum algorithm for identifying counterfeit (different-weight) coins among genuine ones using a weighing-based query model, faster than the best classical strategies.",
    problem: "Given a set of coins where some unknown subset are counterfeit (heavier or lighter), identify the counterfeit coins using the fewest possible weighings.",
    howItWorks: "Uses a quantum query model analogous to Grover-style amplitude amplification, encoding weighing outcomes into a quantum state to narrow down counterfeit coins faster than classical weighing strategies.",
    realWorldImpact: "Primarily of theoretical interest in quantum query complexity research, illustrating how classic combinatorial puzzles can sometimes be reformulated to benefit from quantum speedups.",
  },
  {
    slug: "quantum-collision-finding",
    name: "Quantum Collision Finding (Brassard-Høyer-Tapp)",
    year: "1997",
    inventor: "Brassard, Høyer & Tapp",
    category: "cryptography",
    speedupType: "polynomial",
    difficulty: 4,
    summary: "Finds two inputs that produce the same output from a function (a 'collision') faster than classical methods, with direct implications for hash function security.",
    problem: "Given a function (like a cryptographic hash), find two different inputs that map to the same output — a core building block for breaking certain cryptographic schemes.",
    howItWorks: "Combines classical preprocessing with Grover-style search to locate colliding pairs using roughly the cube root of the number of classical queries needed.",
    realWorldImpact: "Informs security analysis of cryptographic hash functions, helping cryptographers determine appropriate hash output lengths to remain secure even against quantum-equipped attackers.",
  },
  {
    slug: "quantum-gradient-descent",
    name: "Quantum Gradient Descent",
    year: "2017 (Rebentrost, Schuld, Wossnig et al.)",
    inventor: "Rebentrost, Schuld, Wossnig and others",
    category: "machine-learning",
    speedupType: "polynomial",
    difficulty: 5,
    summary: "A quantum approach to the gradient descent optimization technique that underlies most classical machine learning training, offering speedups under specific structural assumptions.",
    problem: "Efficiently finding the minimum of a cost function — the core operation repeated millions of times when training classical machine learning models.",
    howItWorks: "Encodes gradient computations into quantum states using techniques related to the HHL algorithm, exploiting quantum linear algebra subroutines to estimate gradients faster under certain sparsity and conditioning assumptions.",
    realWorldImpact: "Largely theoretical — like other quantum linear algebra speedups, it depends on efficient quantum data loading, which remains a significant unsolved practical bottleneck for real machine learning datasets.",
  },
  {
    slug: "quantum-support-vector-machine",
    name: "Quantum Support Vector Machine",
    year: "2014",
    inventor: "Rebentrost, Mohseni & Lloyd",
    category: "machine-learning",
    speedupType: "exponential",
    difficulty: 5,
    summary: "A quantum version of the classical support vector machine classification algorithm, offering an exponential speedup under specific idealized conditions.",
    problem: "Classifying data points into categories by finding an optimal separating boundary — one of the most widely used classical machine learning techniques.",
    howItWorks: "Uses quantum matrix inversion techniques (related to HHL) to solve the optimization problem underlying support vector machines, assuming the data is already available as an efficiently preparable quantum state.",
    realWorldImpact: "An influential early quantum machine learning proposal, though subsequent research has emphasized that the 'input problem' of loading classical data into quantum states efficiently undermines much of the theoretical speedup in practice.",
  },
  {
    slug: "quantum-anomaly-detection",
    name: "Quantum Anomaly Detection",
    year: "2018",
    inventor: "Multiple contributors, including Liu & Rebentrost",
    category: "machine-learning",
    speedupType: "polynomial",
    difficulty: 4,
    summary: "Quantum approaches to identifying unusual or outlier data points within a larger dataset, relevant to fraud detection and system monitoring.",
    problem: "Identifying data points that deviate significantly from the normal pattern in a dataset, without needing labeled examples of what 'abnormal' looks like.",
    howItWorks: "Uses quantum kernel methods or density estimation techniques to measure how far a data point's quantum-encoded representation differs from the bulk of the dataset.",
    realWorldImpact: "An active research direction for potential applications like fraud detection and network security monitoring, though — like most quantum ML proposals — without demonstrated advantage on real-world datasets yet.",
  },
  {
    slug: "qram-architecture",
    name: "Quantum Random Access Memory (QRAM)",
    year: "2008 (Giovannetti, Lloyd & Maccone)",
    inventor: "Giovannetti, Lloyd & Maccone",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 5,
    summary: "A proposed architecture for accessing classical data in superposition, theoretically required to realize many quantum machine learning speedups in practice.",
    problem: "Efficiently loading classical data into a quantum computer so multiple data points can be queried simultaneously in superposition.",
    howItWorks: "Proposes a tree-like addressing structure for retrieving memory cells in superposition, requiring specialized quantum hardware distinct from a standard quantum processor's qubits.",
    realWorldImpact: "Widely discussed as the 'input problem' bottleneck — many proposed quantum ML and linear algebra speedups assume QRAM exists, but building an efficient, large-scale QRAM remains a major open hardware challenge.",
  },
  {
    slug: "swap-test",
    name: "SWAP Test",
    year: "2001 (Buhrman, Cleve, Watrous & de Wolf)",
    inventor: "Buhrman, Cleve, Watrous & de Wolf",
    category: "foundational",
    speedupType: "none-proven",
    difficulty: 3,
    summary: "A simple but widely used quantum subroutine for estimating how similar two quantum states are, without fully measuring either one.",
    problem: "Determining how similar (or different) two quantum states are — a building block used inside many other quantum algorithms, especially in quantum machine learning.",
    howItWorks: "Uses an auxiliary qubit and a controlled-swap gate between the two states being compared; measuring the auxiliary qubit gives a probability directly related to the overlap between the two states.",
    realWorldImpact: "A foundational subroutine used inside quantum machine learning algorithms (like quantum k-means and quantum SVMs) for similarity comparison, rather than a standalone application.",
  },
  {
    slug: "quantum-k-means",
    name: "Quantum k-Means Clustering",
    year: "2013",
    inventor: "Lloyd, Mohseni & Rebentrost",
    category: "machine-learning",
    speedupType: "exponential",
    difficulty: 4,
    summary: "A quantum version of the classical k-means clustering algorithm, grouping similar data points together using quantum distance estimation techniques.",
    problem: "Partitioning a dataset into clusters of similar items — one of the most common unsupervised machine learning tasks.",
    howItWorks: "Uses quantum subroutines like the SWAP test to estimate distances between data points and cluster centers, potentially reducing the work needed compared to classical distance calculations.",
    realWorldImpact: "Like other early quantum ML proposals, theoretically promising but constrained by the practical challenge of efficiently loading real-world data into quantum states.",
  },
  {
    slug: "linear-combination-of-unitaries",
    name: "Linear Combination of Unitaries (LCU)",
    year: "2012 (Childs & Wiebe)",
    inventor: "Childs & Wiebe",
    category: "simulation",
    speedupType: "exponential",
    difficulty: 5,
    summary: "A general technique for implementing operations that aren't directly unitary by expressing them as a weighted combination of simpler unitary operations.",
    problem: "Many useful mathematical operations in quantum simulation and algorithms aren't directly realizable as quantum gates (which must be unitary) — LCU provides a way around this.",
    howItWorks: "Decomposes a desired (possibly non-unitary) operation into a weighted sum of unitary operations, implementing it probabilistically using extra ancilla qubits and post-selection.",
    realWorldImpact: "An important theoretical tool underlying modern quantum simulation algorithms, including advanced techniques for simulating quantum chemistry and physics beyond basic Trotterization.",
  },
  {
    slug: "quantum-signal-processing",
    name: "Quantum Signal Processing (QSP)",
    year: "2016 (Low & Chuang)",
    inventor: "Low & Chuang",
    category: "simulation",
    speedupType: "exponential",
    difficulty: 5,
    summary: "A unifying mathematical framework for designing highly efficient quantum algorithms by applying polynomial transformations to a quantum operation's eigenvalues.",
    problem: "Designing optimal quantum circuits for applying complex mathematical functions to quantum states, used throughout quantum simulation and quantum linear algebra.",
    howItWorks: "Alternates a fixed quantum operation with carefully chosen single-qubit rotations to effectively apply a target polynomial function to the operation's eigenvalues, achieving near-optimal circuit depth.",
    realWorldImpact: "Considered one of the most important theoretical advances in quantum algorithm design in the past decade, unifying and improving many previously separate quantum algorithms under one framework.",
  },
  {
    slug: "trotter-suzuki-decomposition",
    name: "Trotter-Suzuki Decomposition",
    year: "1959 (Trotter) / 1976 (Suzuki, quantum context: 1996 Lloyd)",
    inventor: "Hale Trotter, Masuo Suzuki, applied to quantum computing by Seth Lloyd",
    category: "simulation",
    speedupType: "exponential",
    difficulty: 4,
    summary: "A technique for approximating the time evolution of a complex quantum system by breaking it into a sequence of simpler, easier-to-implement steps.",
    problem: "Simulating how a quantum system evolves over time, when the full evolution operator is too complex to implement directly as a quantum circuit.",
    howItWorks: "Splits the system's total energy description into simpler pieces, then alternates applying each piece for very short time steps — approximating the full evolution increasingly accurately as the steps get smaller.",
    realWorldImpact: "The foundational method underlying most practical quantum simulation algorithms used in chemistry and materials science applications today, including implementations on real NISQ hardware.",
  },
  {
    slug: "quantum-approximate-counting",
    name: "Quantum Approximate Counting",
    year: "1998 (related to Quantum Counting, simplified variants since)",
    inventor: "Brassard, Høyer, Tapp and later simplifications",
    category: "search",
    speedupType: "quadratic",
    difficulty: 3,
    summary: "Estimates the number of solutions to a search problem approximately, trading some precision for a simpler and often faster quantum circuit than exact quantum counting.",
    problem: "Quickly estimating roughly how many items in a large dataset satisfy a given condition, when an approximate answer is sufficient.",
    howItWorks: "Uses simplified amplitude estimation circuits with fewer required qubits and gates than full quantum phase estimation, trading precision for practicality on near-term hardware.",
    realWorldImpact: "More practical for NISQ-era hardware than the full quantum counting algorithm, useful in statistical estimation tasks where approximate counts are acceptable.",
  },
  {
    slug: "quantum-pagerank",
    name: "Quantum PageRank",
    year: "2012 (Paparo & Martin-Delgado)",
    inventor: "Paparo & Martin-Delgado",
    category: "search",
    speedupType: "none-proven",
    difficulty: 4,
    summary: "A quantum-walk-based reformulation of the classical PageRank algorithm (originally used by Google to rank web pages), offering different ranking behavior rather than a proven speedup.",
    problem: "Ranking nodes in a network (like web pages) by importance, based on the structure of links between them.",
    howItWorks: "Replaces the classical random walk underlying PageRank with a quantum walk, which explores the network differently and can reveal structural features classical PageRank misses, particularly for networks with certain symmetries.",
    realWorldImpact: "Primarily a research tool for studying network structure differently than classical methods, rather than a faster drop-in replacement for existing web search ranking systems.",
  },
  {
    slug: "adiabatic-quantum-computation",
    name: "Adiabatic Quantum Computation",
    year: "2000 (Farhi, Goldstone, Gutmann & Sipser)",
    inventor: "Farhi, Goldstone, Gutmann & Sipser",
    category: "optimization",
    speedupType: "heuristic",
    difficulty: 4,
    summary: "A general-purpose model of quantum computation (closely related to quantum annealing) that encodes a problem's answer as the lowest-energy state of a carefully designed quantum system.",
    problem: "Solving general computational problems by slowly evolving a quantum system from an easy starting configuration toward one encoding the desired answer.",
    howItWorks: "Starts the system in an easily prepared low-energy state and gradually changes its governing equations so that, if done slowly enough, the system stays in its lowest-energy state — which is engineered to represent the problem's solution.",
    realWorldImpact: "Proven theoretically equivalent in computational power to standard gate-based quantum computing, and forms the theoretical basis for quantum annealing hardware like D-Wave's systems.",
  },
  {
    slug: "quantum-zeno-effect-algorithms",
    name: "Quantum Zeno Effect-Based Algorithms",
    year: "2014 (various applications)",
    inventor: "Multiple contributors building on the quantum Zeno effect",
    category: "foundational",
    speedupType: "none-proven",
    difficulty: 4,
    summary: "Algorithms that exploit the quantum Zeno effect — where frequent measurement can effectively 'freeze' a quantum system's evolution — for tasks like quantum state preparation.",
    problem: "Preparing specific quantum states or steering a quantum system's evolution using repeated measurement rather than direct gate control.",
    howItWorks: "Performs frequent, carefully designed measurements that effectively constrain the system to evolve only within a desired subspace, exploiting the physical phenomenon where rapid measurement suppresses change.",
    realWorldImpact: "Used in some specialized state preparation and error suppression techniques, illustrating that measurement itself, usually framed as 'destroying' quantum information, can sometimes be turned into a useful computational tool.",
  },
  {
    slug: "kitaev-six-state-protocol",
    name: "Six-State Quantum Key Distribution Protocol",
    year: "1998 (Bruss)",
    inventor: "Dagmar Bruss",
    category: "cryptography",
    speedupType: "none-proven",
    difficulty: 3,
    summary: "An extension of BB84-style quantum key distribution using six measurement states instead of four, improving security against certain eavesdropping strategies.",
    problem: "Establishing a shared secret key between two parties with even stronger security guarantees against intercept-and-resend eavesdropping attacks than the original BB84 protocol.",
    howItWorks: "Adds a third measurement basis to the standard BB84 setup, increasing the chance that any eavesdropping attempt is detected, at the cost of a higher fraction of discarded key bits.",
    realWorldImpact: "One of several BB84 variants used in research and some commercial QKD systems, illustrating the ongoing refinement of quantum cryptography protocols beyond the original 1984 proposal.",
  },
  {
    slug: "device-independent-qkd",
    name: "Device-Independent Quantum Key Distribution",
    year: "2007 (Acín et al.)",
    inventor: "Acín, Brunner, Gisin, Massar, Pironio & Scarani",
    category: "cryptography",
    speedupType: "none-proven",
    difficulty: 5,
    summary: "A quantum key distribution approach whose security can be guaranteed without trusting the internal workings of the devices used, relying only on observed Bell inequality violations.",
    problem: "Establishing secure communication even when the quantum hardware itself might be compromised, manufactured by an untrusted party, or contain hidden flaws.",
    howItWorks: "Bases security entirely on statistical violations of Bell inequalities observed in the measurement outcomes, rather than assumptions about how the underlying devices work internally.",
    realWorldImpact: "Represents the strongest known security model for quantum cryptography, though current implementations require very high-quality entanglement sources, limiting practical deployment so far.",
  },
  {
    slug: "quantum-digital-signatures",
    name: "Quantum Digital Signatures",
    year: "2001 (Gottesman & Chuang)",
    inventor: "Gottesman & Chuang",
    category: "cryptography",
    speedupType: "none-proven",
    difficulty: 4,
    summary: "A quantum protocol allowing a sender to digitally 'sign' a message such that recipients can verify its authenticity, with security guaranteed by quantum mechanics rather than computational assumptions.",
    problem: "Proving that a message genuinely came from a specific sender and hasn't been tampered with, without relying on classical cryptographic assumptions that quantum computers might eventually break.",
    howItWorks: "Distributes quantum states that encode signature information, exploiting the no-cloning theorem to prevent forgery, while classical verification steps confirm the message's authenticity.",
    realWorldImpact: "An active research area for ensuring long-term security of digitally signed documents and communications in a future where classical signature schemes might be vulnerable to quantum attacks.",
  },
  {
    slug: "quantum-secret-sharing",
    name: "Quantum Secret Sharing",
    year: "1999 (Hillery, Bužek & Berthiaume)",
    inventor: "Hillery, Bužek & Berthiaume",
    category: "cryptography",
    speedupType: "none-proven",
    difficulty: 4,
    summary: "A protocol for splitting a secret among multiple parties using entangled quantum states, such that the secret can only be reconstructed if a sufficient number of parties cooperate.",
    problem: "Distributing a sensitive piece of information among several people so that no single person (or small group) can access it alone, but a sufficient quorum acting together can.",
    howItWorks: "Distributes shares of a multi-party entangled state to each participant; reconstructing the original secret requires combining measurements from enough participants according to the protocol's threshold rules.",
    realWorldImpact: "Relevant to securing highly sensitive information (like nuclear launch codes or critical cryptographic keys) where distributed trust and quantum-level security guarantees both matter.",
  },
  {
    slug: "quantum-walk-graph-isomorphism",
    name: "Quantum Walk Algorithms for Graph Isomorphism",
    year: "2008 (Douglas & Wang, and others)",
    inventor: "Multiple contributors including Douglas & Wang",
    category: "foundational",
    speedupType: "heuristic",
    difficulty: 5,
    summary: "Quantum walk-based approaches to determining whether two graphs have identical structure, a notoriously difficult classical problem with unclear classical complexity.",
    problem: "Determining whether two graphs (networks of nodes and edges) are structurally identical, even if drawn differently — a problem with no known efficient classical algorithm for the general case.",
    howItWorks: "Compares the statistical signatures produced by quantum walks evolving on each graph; matching signatures suggest the graphs may be isomorphic, though this is heuristic rather than a guaranteed proof.",
    realWorldImpact: "An active area of quantum algorithms research; since the classical complexity of graph isomorphism itself is unresolved, any quantum speedup claims here remain especially carefully scrutinized.",
  },
  {
    slug: "quantum-approximate-tsp",
    name: "Quantum Approaches to the Traveling Salesman Problem",
    year: "2017 onward (various QAOA-based formulations)",
    inventor: "Multiple contributors building on QAOA",
    category: "optimization",
    speedupType: "heuristic",
    difficulty: 4,
    summary: "Adaptations of QAOA and related quantum optimization algorithms to the classic traveling salesman problem — finding the shortest route visiting a set of locations exactly once.",
    problem: "Finding the shortest possible route that visits every location in a given set exactly once and returns to the start — a famously hard combinatorial optimization problem.",
    howItWorks: "Encodes valid routes as quantum states using carefully designed cost functions, then applies QAOA-style alternating quantum and classical optimization steps to find low-cost (short) routes.",
    realWorldImpact: "Frequently used as a benchmark problem for testing near-term quantum optimization hardware and algorithms, including in logistics industry pilot studies.",
  },
  {
    slug: "quantum-max-cut",
    name: "Quantum Max-Cut Algorithms",
    year: "2014 (QAOA's original demonstration problem)",
    inventor: "Farhi, Goldstone & Gutmann (via QAOA)",
    category: "optimization",
    speedupType: "heuristic",
    difficulty: 3,
    summary: "Quantum approaches to the Max-Cut problem — partitioning a network's nodes into two groups to maximize the number of connections between the groups — the original benchmark problem for QAOA.",
    problem: "Dividing a network into two groups such that the number of connections crossing between the groups is as large as possible.",
    howItWorks: "Encodes possible partitions as quantum states, using QAOA's alternating optimization structure to search for partitions with a high cut value.",
    realWorldImpact: "The most commonly used benchmark for testing and comparing QAOA implementations across different quantum hardware platforms, due to its simple, well-understood classical structure.",
  },
  {
    slug: "quantum-belief-propagation",
    name: "Quantum Belief Propagation",
    year: "2007 (Leifer & Poulin)",
    inventor: "Leifer & Poulin",
    category: "machine-learning",
    speedupType: "heuristic",
    difficulty: 5,
    summary: "A quantum generalization of the classical belief propagation algorithm used for probabilistic inference in graphical models, relevant to both quantum error correction and quantum machine learning.",
    problem: "Efficiently estimating probabilities in complex networks of interdependent variables — a core task in classical statistical inference and machine learning.",
    howItWorks: "Generalizes classical message-passing inference rules to quantum states, propagating quantum 'belief' information across a network structure to estimate quantum marginal probabilities.",
    realWorldImpact: "Has direct applications in decoding certain quantum error-correcting codes, connecting classical inference theory to practical quantum error correction implementations.",
  },
  {
    slug: "quantum-optimal-transport",
    name: "Quantum Algorithms for Optimal Transport",
    year: "2019 onward",
    inventor: "Multiple contributors",
    category: "optimization",
    speedupType: "polynomial",
    difficulty: 5,
    summary: "Quantum approaches to the optimal transport problem — finding the most efficient way to move or transform one distribution of resources into another — relevant to logistics and machine learning.",
    problem: "Determining the most efficient way to redistribute resources, mass, or probability from one configuration to a target configuration, minimizing total movement cost.",
    howItWorks: "Reformulates the classical optimal transport linear program using quantum optimization or quantum linear algebra subroutines, aiming to reduce the computational cost of large-scale transport problems.",
    realWorldImpact: "An emerging research area connecting quantum computing to a mathematical framework already widely used in classical machine learning, economics, and logistics planning.",
  },
  {
    slug: "quantum-monte-carlo-integration",
    name: "Quantum Monte Carlo Integration",
    year: "2000 (Brassard, Høyer, Mosca & Tapp, foundational; many applications since)",
    inventor: "Built on Quantum Amplitude Estimation",
    category: "simulation",
    speedupType: "quadratic",
    difficulty: 3,
    summary: "Applies quantum amplitude estimation specifically to numerical integration problems, offering a quadratic speedup over classical Monte Carlo integration methods.",
    problem: "Numerically estimating the value of a complex integral, a task that classically often relies on random (Monte Carlo) sampling when direct calculation isn't feasible.",
    howItWorks: "Encodes the function being integrated into a quantum circuit's amplitudes, then uses amplitude estimation to extract the integral's value with quadratically fewer samples than classical Monte Carlo methods.",
    realWorldImpact: "Directly applicable to the same finance, engineering, and scientific computing problems that already rely heavily on classical Monte Carlo integration — one of the more concretely useful near-term quantum algorithm categories.",
  },
  {
    slug: "quantum-semidefinite-programming",
    name: "Quantum Algorithms for Semidefinite Programming",
    year: "2017 (Brandão & Svore)",
    inventor: "Brandão & Svore",
    category: "optimization",
    speedupType: "polynomial",
    difficulty: 5,
    summary: "Quantum algorithms for solving semidefinite programs — a powerful and widely used class of optimization problems — offering polynomial speedups under certain conditions.",
    problem: "Solving semidefinite programs, a generalization of linear programming used throughout combinatorial optimization, control theory, and machine learning.",
    howItWorks: "Uses quantum Gibbs sampling and amplitude estimation techniques to approximate solutions to the underlying optimization problem faster than the best known classical algorithms in certain regimes.",
    realWorldImpact: "Primarily theoretical at this stage, but semidefinite programming itself is so broadly used across optimization and machine learning that even modest practical speedups could have wide-reaching effects.",
  },
  {
    slug: "iterative-phase-estimation",
    name: "Iterative Quantum Phase Estimation",
    year: "2007 (Dobšíček et al.)",
    inventor: "Dobšíček, Johansson, Shimoni & Nori",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 4,
    summary: "A resource-efficient variant of standard quantum phase estimation that uses a single ancilla qubit repeatedly, instead of many qubits at once — better suited to near-term hardware.",
    problem: "Estimating the phase associated with a quantum operation's eigenstate (as in standard phase estimation), but using significantly fewer physical qubits.",
    howItWorks: "Repeats a single-qubit measurement-and-feedback procedure multiple times, extracting one bit of phase information per round instead of using a large register of qubits simultaneously.",
    realWorldImpact: "Makes phase estimation — a key subroutine in Shor's Algorithm and quantum chemistry simulation — more practical on today's qubit-limited NISQ hardware.",
  },
  {
    slug: "quantum-error-mitigation",
    name: "Quantum Error Mitigation Techniques",
    year: "2017 onward (Temme, Bravyi, Gambetta and others)",
    inventor: "Temme, Bravyi & Gambetta, and others",
    category: "foundational",
    speedupType: "none-proven",
    difficulty: 3,
    summary: "A family of techniques for reducing the impact of noise on NISQ-era quantum computations without requiring full quantum error correction's heavy qubit overhead.",
    problem: "Getting more accurate results from today's noisy quantum hardware, without the enormous number of extra physical qubits full error correction would require.",
    howItWorks: "Techniques like zero-noise extrapolation run the same circuit at deliberately varied noise levels and extrapolate back to an estimated zero-noise result, rather than directly correcting errors during computation.",
    realWorldImpact: "Already widely used in practice on real NISQ hardware today (including in VQE and QAOA experiments), serving as a practical bridge until full quantum error correction becomes feasible at scale.",
  },
  {
    slug: "quantum-natural-gradient",
    name: "Quantum Natural Gradient Descent",
    year: "2020 (Stokes, Izaac, Killoran & Carleo)",
    inventor: "Stokes, Izaac, Killoran & Carleo",
    category: "optimization",
    speedupType: "heuristic",
    difficulty: 4,
    summary: "An improved optimization technique for training variational quantum algorithms like VQE and QAOA, accounting for the underlying geometry of quantum state space to converge faster.",
    problem: "Efficiently tuning the adjustable parameters in hybrid quantum-classical algorithms (like VQE), where standard optimization techniques often converge slowly or get stuck.",
    howItWorks: "Adjusts the classical optimization step size and direction based on the quantum state space's natural geometric structure (the quantum Fisher information metric), rather than treating all parameter directions equally.",
    realWorldImpact: "Has demonstrated meaningfully faster convergence for training variational quantum algorithms in practice, directly improving the practicality of NISQ-era quantum chemistry and optimization applications.",
  },
  {
    slug: "quantum-imaginary-time-evolution",
    name: "Quantum Imaginary Time Evolution (QITE)",
    year: "2019 (Motta, Sun, Tan et al.)",
    inventor: "Motta, Sun, Tan and collaborators",
    category: "simulation",
    speedupType: "heuristic",
    difficulty: 5,
    summary: "An alternative to VQE for finding a quantum system's ground state, using a mathematical technique borrowed from statistical mechanics adapted to run on quantum hardware.",
    problem: "Finding the lowest-energy (ground) state of a quantum system, similar to VQE's goal, but using a different mathematical approach that can sometimes avoid VQE's optimization difficulties.",
    howItWorks: "Simulates evolution in 'imaginary time' (a mathematical trick from statistical mechanics) which naturally drives a quantum system toward its ground state, implemented through a sequence of small quantum circuit updates.",
    realWorldImpact: "An active alternative to VQE for near-term quantum chemistry simulation, particularly useful in cases where VQE's classical optimization step struggles to converge.",
  },
];

export function getAlgorithmBySlug(slug: string) {
  return algorithms.find((a) => a.slug === slug);
}
