export type Algorithm = {
  slug: string;
  name: string;
  year: string;
  inventor: string;
  category: "factoring" | "search" | "simulation" | "optimization" | "machine-learning" | "cryptography" | "foundational";
  speedupType: "exponential" | "quadratic" | "polynomial" | "heuristic" | "none-proven";
  difficulty: 1 | 2 | 3 | 4 | 5;
  summary: string;
  problem: string;
  howItWorks: string;
  realWorldImpact: string;
  relatedLearnSlug?: string;
};

export const algorithms: Algorithm[] = [
  {
    slug: "shors-algorithm",
    name: "Shor's Algorithm",
    year: "1994",
    inventor: "Peter Shor",
    category: "factoring",
    speedupType: "exponential",
    difficulty: 4,
    summary: "Factors large numbers exponentially faster than any known classical algorithm, threatening RSA encryption.",
    problem: "Finding the prime factors of a large composite number — believed to be intractable for classical computers at scale.",
    howItWorks: "Transforms factoring into a period-finding problem, solved efficiently using the Quantum Fourier Transform, then recovers factors via classical post-processing.",
    realWorldImpact: "Directly motivates post-quantum cryptography; would break RSA and similar encryption if run on a large enough fault-tolerant quantum computer.",
    relatedLearnSlug: "shors-algorithm",
  },
  {
    slug: "grovers-algorithm",
    name: "Grover's Algorithm",
    year: "1996",
    inventor: "Lov Grover",
    category: "search",
    speedupType: "quadratic",
    difficulty: 3,
    summary: "Searches unsorted data in roughly √N steps instead of N, using amplitude amplification.",
    problem: "Finding a specific item in an unsorted list or database without any shortcut like sorting.",
    howItWorks: "Repeatedly applies an oracle that marks the correct answer, then amplifies its probability through reflection operations, concentrating probability onto the right answer.",
    realWorldImpact: "Broadly applicable to search and optimization problems; also halves the effective key strength of certain symmetric encryption schemes.",
    relatedLearnSlug: "grovers-algorithm",
  },
  {
    slug: "deutsch-jozsa",
    name: "Deutsch-Jozsa Algorithm",
    year: "1992",
    inventor: "David Deutsch & Richard Jozsa",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 3,
    summary: "The first algorithm to prove a quantum computer could solve a problem exponentially faster than any classical deterministic algorithm.",
    problem: "Determining whether a given function is 'constant' (same output for all inputs) or 'balanced' (different outputs for half the inputs).",
    howItWorks: "Uses superposition to evaluate the function on all inputs simultaneously, then uses interference so a single measurement reveals whether the function is constant or balanced.",
    realWorldImpact: "Mainly historical and educational — it proved quantum speedup was possible in principle, paving the way for Shor's and Grover's algorithms, though the problem itself has limited practical use.",
  },
  {
    slug: "simons-algorithm",
    name: "Simon's Algorithm",
    year: "1994",
    inventor: "Daniel Simon",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 4,
    summary: "Finds a hidden pattern (period) in a function exponentially faster than classical methods, directly inspiring Shor's Algorithm.",
    problem: "Given a function with a hidden 'XOR-periodicity,' find the hidden period.",
    howItWorks: "Uses superposition and the structure of the problem to extract the hidden period using only a linear number of quantum queries, versus an exponential number classically.",
    realWorldImpact: "Primarily of theoretical importance — Simon's problem directly inspired Peter Shor's approach to factoring, making it a key stepping stone in quantum algorithm history.",
  },
  {
    slug: "quantum-fourier-transform",
    name: "Quantum Fourier Transform (QFT)",
    year: "1994",
    inventor: "Don Coppersmith (building on classical FFT)",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 4,
    summary: "The quantum analog of the discrete Fourier transform, performed exponentially faster than the classical Fast Fourier Transform.",
    problem: "Transforming a quantum state to reveal its underlying periodicity or frequency structure.",
    howItWorks: "Uses a sequence of Hadamard and controlled-phase gates to transform amplitudes, extracting frequency information encoded across a register of qubits.",
    realWorldImpact: "A core subroutine used inside Shor's Algorithm and quantum phase estimation; rarely used as a standalone algorithm but essential as a building block.",
  },
  {
    slug: "quantum-phase-estimation",
    name: "Quantum Phase Estimation (QPE)",
    year: "1995",
    inventor: "Alexei Kitaev",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 4,
    summary: "Estimates the eigenvalue (phase) associated with a quantum operation, a critical building block for many other quantum algorithms.",
    problem: "Determining the precise phase associated with an eigenstate of a unitary quantum operation.",
    howItWorks: "Combines controlled application of the unitary operation with the inverse Quantum Fourier Transform to extract the phase to high precision.",
    realWorldImpact: "Used inside Shor's Algorithm, quantum chemistry simulations, and the HHL algorithm for solving linear systems — a true workhorse subroutine.",
  },
  {
    slug: "vqe",
    name: "Variational Quantum Eigensolver (VQE)",
    year: "2014",
    inventor: "Peruzzo et al.",
    category: "simulation",
    speedupType: "heuristic",
    difficulty: 3,
    summary: "A hybrid quantum-classical algorithm for finding the lowest energy state of a molecule or material, designed to work on noisy near-term hardware.",
    problem: "Finding the ground-state energy of a quantum system (like a molecule), which is exponentially hard to compute classically as system size grows.",
    howItWorks: "A quantum computer prepares trial states and measures their energy, while a classical optimizer iteratively adjusts parameters to minimize that energy — splitting the work between quantum and classical hardware.",
    realWorldImpact: "One of the most promising NISQ-era applications, actively used in early quantum chemistry and materials science research, including drug discovery exploration.",
    relatedLearnSlug: "quantum-algorithms",
  },
  {
    slug: "qaoa",
    name: "Quantum Approximate Optimization Algorithm (QAOA)",
    year: "2014",
    inventor: "Farhi, Goldstone & Gutmann",
    category: "optimization",
    speedupType: "heuristic",
    difficulty: 3,
    summary: "A hybrid algorithm for finding approximate solutions to combinatorial optimization problems on near-term quantum hardware.",
    problem: "Approximately solving optimization problems like Max-Cut, scheduling, or routing — problems with many possible solutions and no easy way to find the best one.",
    howItWorks: "Alternates between quantum operations that explore the solution space and classical optimization that tunes parameters, gradually converging on better solutions.",
    realWorldImpact: "Explored for portfolio optimization, logistics routing, and scheduling problems; whether it offers genuine advantage over the best classical heuristics remains an active research question.",
  },
  {
    slug: "hhl-algorithm",
    name: "HHL Algorithm",
    year: "2009",
    inventor: "Harrow, Hassidim & Lloyd",
    category: "machine-learning",
    speedupType: "exponential",
    difficulty: 5,
    summary: "Solves systems of linear equations exponentially faster than classical methods, under specific conditions.",
    problem: "Solving a system of linear equations (Ax = b) — a problem underlying enormous amounts of scientific computing and machine learning.",
    howItWorks: "Encodes the linear system into a quantum state, uses quantum phase estimation to find eigenvalues, and inverts them to construct the solution — all without ever writing out the full solution vector classically.",
    realWorldImpact: "Has significant caveats (requires the matrix to be 'sparse' and well-conditioned, and the output is a quantum state, not a classical answer), but is foundational to quantum machine learning research.",
  },
  {
    slug: "quantum-walk-search",
    name: "Quantum Walk Algorithms",
    year: "2003 (Childs et al.)",
    inventor: "Multiple contributors",
    category: "search",
    speedupType: "polynomial",
    difficulty: 4,
    summary: "The quantum analog of a classical random walk, used to search graphs and networks faster than classical methods in specific structured cases.",
    problem: "Searching or traversing a large graph or network structure to find a target node or path.",
    howItWorks: "Exploits quantum superposition and interference to spread probability across a graph differently than a classical random walk, in some cases reaching target nodes quadratically faster.",
    realWorldImpact: "Used in specialized search applications and as a building block for some optimization and machine learning algorithms; less broadly known than Grover's but mathematically related.",
  },
  {
    slug: "quantum-counting",
    name: "Quantum Counting",
    year: "1998",
    inventor: "Brassard, Høyer & Tapp",
    category: "search",
    speedupType: "quadratic",
    difficulty: 3,
    summary: "Estimates the number of solutions to a search problem, combining Grover's Algorithm with quantum phase estimation.",
    problem: "Determining how many items in a dataset satisfy a given condition, without checking every item individually.",
    howItWorks: "Uses the structure of Grover's amplitude amplification combined with phase estimation to extract a count rather than a single answer.",
    realWorldImpact: "Useful in cryptanalysis and statistical estimation tasks where the quantity of solutions matters as much as finding one example.",
  },
  {
    slug: "quantum-amplitude-estimation",
    name: "Quantum Amplitude Estimation",
    year: "2000",
    inventor: "Brassard, Høyer, Mosca & Tapp",
    category: "optimization",
    speedupType: "quadratic",
    difficulty: 4,
    summary: "Estimates an unknown probability or expected value quadratically faster than classical Monte Carlo sampling.",
    problem: "Estimating the probability of an event or the expected value of a function, traditionally done via repeated random sampling (Monte Carlo methods).",
    howItWorks: "Combines amplitude amplification with phase estimation to extract a probability estimate with quadratically fewer samples than classical Monte Carlo.",
    realWorldImpact: "A leading candidate for near-term financial applications like risk analysis and options pricing, where Monte Carlo methods are already heavily used classically.",
  },
  {
    slug: "quantum-teleportation-protocol",
    name: "Quantum Teleportation Protocol",
    year: "1993",
    inventor: "Bennett, Brassard, Crépeau, Jozsa, Peres & Wootters",
    category: "foundational",
    speedupType: "none-proven",
    difficulty: 3,
    summary: "A protocol for transferring an unknown quantum state from one location to another using entanglement and classical communication.",
    problem: "Moving a fragile, unknown quantum state to a distant location without physically transporting the particle itself.",
    howItWorks: "Uses a pre-shared entangled pair plus a measurement and classical message to reconstruct the original quantum state at the destination, destroying the original in the process (consistent with the no-cloning theorem).",
    realWorldImpact: "Foundational to quantum networking and the long-term vision of a quantum internet; experimentally demonstrated over increasing distances, including via satellite.",
  },
  {
    slug: "bb84-protocol",
    name: "BB84 Quantum Key Distribution",
    year: "1984",
    inventor: "Bennett & Brassard",
    category: "cryptography",
    speedupType: "none-proven",
    difficulty: 2,
    summary: "The first quantum key distribution protocol, allowing two parties to generate a shared secret key with security guaranteed by physics rather than mathematical assumptions.",
    problem: "Establishing a shared secret encryption key between two parties in a way that reveals any eavesdropping attempt.",
    howItWorks: "Encodes key bits in the polarization of single photons; any attempt to intercept and measure them disturbs the quantum state in a detectable way, revealing eavesdropping.",
    realWorldImpact: "Commercially deployed today in specific high-security contexts (banking, government); the conceptual foundation for all quantum cryptography that followed.",
  },
  {
    slug: "e91-protocol",
    name: "E91 Quantum Key Distribution",
    year: "1991",
    inventor: "Artur Ekert",
    category: "cryptography",
    speedupType: "none-proven",
    difficulty: 3,
    summary: "A quantum key distribution protocol based on entangled particle pairs and Bell inequality tests rather than single-photon polarization.",
    problem: "Establishing a shared secret key with security based directly on the foundational properties of quantum entanglement.",
    howItWorks: "Distributes entangled particle pairs to both parties; measuring them in different bases and checking for Bell inequality violations both generates the key and detects eavesdropping.",
    realWorldImpact: "Connects practical cryptography directly to the foundational tests of quantum mechanics (Bell's theorem), and underlies some modern device-independent QKD schemes.",
  },
  {
    slug: "quantum-supremacy-sampling",
    name: "Random Circuit Sampling",
    year: "2019 (Google demonstration)",
    inventor: "Google Quantum AI team",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 4,
    summary: "A computational task used to demonstrate 'quantum supremacy' — sampling outputs from a deliberately complex, randomly generated quantum circuit.",
    problem: "Generating samples from the probability distribution produced by a large random quantum circuit — a task believed exponentially hard to simulate classically.",
    howItWorks: "Runs a circuit of random quantum gates across many qubits, then measures the output, repeating many times to build a statistical sample of the underlying probability distribution.",
    realWorldImpact: "Has no direct practical application — its significance was purely as a benchmark demonstrating quantum hardware capability, and the 'supremacy' claim was later contested by improved classical simulations.",
  },
  {
    slug: "quantum-error-correction-codes",
    name: "Quantum Error-Correcting Codes (Shor Code, Surface Code)",
    year: "1995 (Shor Code) / 2002 (Surface Code popularized)",
    inventor: "Peter Shor; Kitaev and others for surface codes",
    category: "foundational",
    speedupType: "none-proven",
    difficulty: 5,
    summary: "Algorithms and encoding schemes for protecting quantum information from errors by spreading it across multiple physical qubits.",
    problem: "Protecting fragile quantum information from decoherence and gate errors without violating the no-cloning theorem.",
    howItWorks: "Encodes one logical qubit across many physical qubits in an entangled configuration, allowing errors to be detected and corrected via syndrome measurements without directly observing the protected quantum information.",
    realWorldImpact: "The central technology required for fault-tolerant quantum computing at scale; without it, large quantum algorithms like Shor's cannot run reliably on real hardware.",
    relatedLearnSlug: "quantum-error-correction",
  },
  {
    slug: "quantum-pca",
    name: "Quantum Principal Component Analysis",
    year: "2014",
    inventor: "Lloyd, Mohseni & Rebentrost",
    category: "machine-learning",
    speedupType: "exponential",
    difficulty: 5,
    summary: "A quantum algorithm for identifying the dominant patterns (principal components) in data, with potential exponential speedup under specific conditions.",
    problem: "Finding the most significant directions of variation in high-dimensional data — a fundamental task in data analysis and machine learning.",
    howItWorks: "Uses quantum phase estimation on a density matrix representing the data to extract eigenvalues and eigenvectors corresponding to principal components.",
    realWorldImpact: "Largely theoretical at present — requires efficient quantum state preparation from classical data, which remains a significant practical bottleneck (sometimes called the 'input problem').",
  },
  {
    slug: "quantum-annealing",
    name: "Quantum Annealing",
    year: "1989 (theory) / 2011 (first commercial hardware)",
    inventor: "Apolloni, Carlucci & Cerf (theory); D-Wave Systems (hardware)",
    category: "optimization",
    speedupType: "heuristic",
    difficulty: 3,
    summary: "A specialized, non-gate-based quantum computing approach that finds low-energy solutions to optimization problems by gradually evolving a quantum system.",
    problem: "Finding near-optimal solutions to combinatorial optimization problems (like scheduling, routing, or portfolio selection).",
    howItWorks: "Starts qubits in a simple, easily prepared quantum state and slowly evolves the system toward a final configuration encoding the problem, exploiting quantum tunneling to escape local minima that would trap classical methods.",
    realWorldImpact: "Commercially available today via D-Wave's quantum annealers, used in early-stage optimization research, though whether it provides genuine quantum advantage over classical heuristics remains debated.",
  },
  {
    slug: "boson-sampling",
    name: "Boson Sampling",
    year: "2011",
    inventor: "Aaronson & Arkhipov",
    category: "foundational",
    speedupType: "exponential",
    difficulty: 4,
    summary: "A specialized computational task using photons (rather than qubits) believed to be exponentially hard to simulate classically, proposed as a near-term path to demonstrating quantum advantage.",
    problem: "Sampling from the output distribution of identical photons passing through a network of optical components — a task with deep connections to permanent calculations in linear algebra.",
    howItWorks: "Sends single photons into a network of beam splitters and mirrors, then measures where they emerge; the resulting statistics are exponentially hard to compute classically as photon number grows.",
    realWorldImpact: "Demonstrated experimentally at increasing scale (notably China's Jiuzhang photonic experiments); like random circuit sampling, primarily valuable as a quantum advantage benchmark rather than a practical application.",
  },
];

export function getAlgorithmBySlug(slug: string) {
  return algorithms.find((a) => a.slug === slug);
}
