export type ExamQuestion = {
  id: number;
  set: number; // 1-20
  question: string;
  options: [string, string, string];
  correct: 0 | 1 | 2;
  explanation: string;
};

export const questionPool: ExamQuestion[] = [
  // SET 1 — Fundamentals
  { id: 1, set: 1, question: "What is a qubit?", options: ["A classical binary digit", "The basic unit of quantum information that can exist in superposition", "A unit of quantum memory storage"], correct: 1, explanation: "A qubit is the fundamental unit of quantum information, capable of superposition of |0⟩ and |1⟩." },
  { id: 2, set: 1, question: "What does superposition mean for a qubit?", options: ["The qubit is secretly either 0 or 1", "The qubit exists in a genuine combination of 0 and 1 simultaneously", "The qubit alternates rapidly between 0 and 1"], correct: 1, explanation: "Superposition is a genuine quantum state — both possibilities coexist with probability amplitudes until measurement." },
  { id: 3, set: 1, question: "What happens when a qubit in superposition is measured?", options: ["It remains in superposition", "It collapses to a definite 0 or 1 with probabilities given by its amplitudes", "It produces both 0 and 1 simultaneously"], correct: 1, explanation: "Measurement causes wave function collapse — the qubit becomes a definite classical value." },
  { id: 4, set: 1, question: "What is quantum entanglement?", options: ["Two qubits that are physically connected by wire", "A correlation between qubits where measuring one instantly determines the other", "A process of copying quantum information"], correct: 1, explanation: "Entanglement creates correlations beyond classical limits — confirmed by Bell inequality violations." },
  { id: 5, set: 1, question: "Which quantum mechanical phenomenon do algorithms use to amplify correct answers?", options: ["Superposition", "Entanglement", "Quantum interference"], correct: 2, explanation: "Quantum interference allows amplitudes to add constructively (boosting correct answers) or destructively (canceling wrong ones)." },
  { id: 6, set: 1, question: "What is decoherence?", options: ["A quantum algorithm optimization technique", "Loss of quantum properties due to environmental interaction", "A type of quantum error correction code"], correct: 1, explanation: "Decoherence occurs when a qubit interacts with its environment, destroying its quantum superposition." },
  { id: 7, set: 1, question: "What does NISQ stand for?", options: ["Non-Integrated Sequential Quantum", "Noisy Intermediate-Scale Quantum", "Networked Integrated Superposition Qubits"], correct: 1, explanation: "NISQ describes today's era of quantum hardware — tens to thousands of qubits, too noisy for full error correction." },
  { id: 8, set: 1, question: "Which gate creates superposition from a |0⟩ state?", options: ["Pauli-X gate", "Hadamard gate", "CNOT gate"], correct: 1, explanation: "The Hadamard gate transforms |0⟩ into (|0⟩+|1⟩)/√2 — an equal superposition." },
  { id: 9, set: 1, question: "What is the Pauli-X gate equivalent to in classical computing?", options: ["AND gate", "OR gate", "NOT gate"], correct: 2, explanation: "The Pauli-X gate flips |0⟩ to |1⟩ and |1⟩ to |0⟩, making it the quantum analog of the classical NOT gate." },
  { id: 10, set: 1, question: "What does the CNOT gate do?", options: ["Copies one qubit to another", "Flips the target qubit only if the control qubit is |1⟩", "Measures both qubits simultaneously"], correct: 1, explanation: "CNOT (Controlled-NOT) flips the target qubit conditionally on the control qubit being |1⟩. It creates entanglement." },
  { id: 11, set: 1, question: "What two gates create a Bell state from |00⟩?", options: ["X then Z", "H then CNOT", "Z then H"], correct: 1, explanation: "Hadamard on qubit 0 creates superposition, then CNOT entangles both qubits into a Bell state." },
  { id: 12, set: 1, question: "What is a quantum circuit?", options: ["A physical electronic circuit inside a quantum computer", "A sequence of quantum gates applied to qubits, followed by measurement", "A diagram of qubit connectivity"], correct: 1, explanation: "A quantum circuit is the standard representation for quantum algorithms — gates applied in sequence, then measured." },
  { id: 13, set: 1, question: "Are quantum gates reversible?", options: ["No, like classical gates", "Yes, all quantum gates are reversible (unitary)", "Only single-qubit gates are reversible"], correct: 1, explanation: "All quantum gates are unitary transformations, which are inherently reversible. This contrasts with most classical logic gates." },
  { id: 14, set: 1, question: "What does T1 measure in quantum hardware?", options: ["Gate operation speed", "Energy relaxation time of a qubit", "Total qubit count"], correct: 1, explanation: "T1 (longitudinal relaxation time) measures how long before a |1⟩ qubit decays to |0⟩ due to energy loss." },
  { id: 15, set: 1, question: "What is gate fidelity?", options: ["The speed of a quantum gate", "How closely a physical gate matches the ideal mathematical operation", "The number of gates in a circuit"], correct: 1, explanation: "Gate fidelity (expressed as a percentage) measures how accurately a physical gate implements the ideal unitary." },

  // SET 2 — Algorithms
  { id: 16, set: 2, question: "What speedup does Grover's Algorithm offer over classical unstructured search?", options: ["Exponential speedup", "Quadratic speedup — O(√N) vs O(N)", "Linear speedup"], correct: 1, explanation: "Grover's Algorithm searches N items in O(√N) steps. This quadratic speedup is proven optimal for unstructured search." },
  { id: 17, set: 2, question: "What type of problem does Shor's Algorithm solve?", options: ["Unstructured search", "Integer factoring", "Linear systems of equations"], correct: 1, explanation: "Shor's Algorithm factors large integers exponentially faster than any known classical algorithm." },
  { id: 18, set: 2, question: "Which encryption standard is most directly threatened by Shor's Algorithm?", options: ["AES-256", "RSA", "SHA-256"], correct: 1, explanation: "RSA security relies on the computational difficulty of factoring large integers — exactly what Shor's Algorithm solves efficiently." },
  { id: 19, set: 2, question: "What does VQE stand for?", options: ["Variable Quantum Experiment", "Variational Quantum Eigensolver", "Virtual Quantum Environment"], correct: 1, explanation: "VQE (Variational Quantum Eigensolver) is a hybrid quantum-classical algorithm for finding molecular ground-state energies." },
  { id: 20, set: 2, question: "What is VQE primarily used for?", options: ["Breaking encryption", "Quantum chemistry and molecular simulation", "Machine learning classification"], correct: 1, explanation: "VQE is one of the most credible near-term quantum applications — finding ground-state energies for molecular simulation." },
  { id: 21, set: 2, question: "What does QAOA stand for?", options: ["Quantum Approximate Optimization Algorithm", "Quantum Assisted Output Analysis", "Qubit Alignment Optimization Approach"], correct: 0, explanation: "QAOA (Quantum Approximate Optimization Algorithm) targets combinatorial optimization problems like Max-Cut and routing." },
  { id: 22, set: 2, question: "What is the role of the oracle in Grover's Algorithm?", options: ["It measures the qubits", "It marks the target item by flipping its phase", "It creates the initial superposition"], correct: 1, explanation: "The oracle applies a phase flip to the target item's amplitude, setting up the diffusion operator to amplify it." },
  { id: 23, set: 2, question: "How many times must Grover's oracle be applied to find an item in N=100 items?", options: ["100 times", "Approximately 10 times (√100)", "50 times"], correct: 1, explanation: "Grover's Algorithm requires approximately π√N/4 ≈ √N oracle calls. For N=100, that's approximately 10 iterations." },
  { id: 24, set: 2, question: "What is quantum phase estimation used for?", options: ["Measuring qubit errors", "Extracting eigenvalues of a unitary operator", "Creating Bell states"], correct: 1, explanation: "QPE extracts the phase (eigenvalue) of a unitary — a key subroutine inside Shor's Algorithm and quantum chemistry." },
  { id: 25, set: 2, question: "What is the HHL algorithm designed to solve?", options: ["Integer factoring", "Linear systems of equations Ax=b", "Graph coloring problems"], correct: 1, explanation: "HHL (Harrow-Hassidim-Lloyd) solves linear systems exponentially faster than classical methods under specific conditions." },
  { id: 26, set: 2, question: "What is a hybrid quantum-classical algorithm?", options: ["An algorithm that runs only on classical computers", "An algorithm that uses both quantum and classical computation iteratively", "An algorithm that simulates quantum on classical hardware"], correct: 1, explanation: "Hybrid algorithms like VQE and QAOA use quantum processors for specific subroutines while classical optimizers handle parameter tuning." },
  { id: 27, set: 2, question: "What is the Deutsch-Jozsa algorithm the first to demonstrate?", options: ["Quantum error correction", "A provable speedup over classical algorithms", "Quantum key distribution"], correct: 1, explanation: "Deutsch-Jozsa was the first quantum algorithm to demonstrate a provable (exponential) speedup — determining if a function is constant or balanced." },
  { id: 28, set: 2, question: "What is amplitude amplification in quantum computing?", options: ["Increasing qubit count", "A technique to boost the probability of measuring a desired outcome", "Amplifying the voltage of quantum signals"], correct: 1, explanation: "Amplitude amplification generalizes Grover's approach — marking a target state and reflecting around the average to boost its probability." },
  { id: 29, set: 2, question: "Which algorithm is most promising for near-term drug discovery applications?", options: ["Shor's Algorithm", "VQE for molecular ground-state energy calculation", "Grover's Algorithm"], correct: 1, explanation: "VQE-based quantum chemistry simulation is widely considered one of the most credible near-term quantum computing applications." },
  { id: 30, set: 2, question: "What does SWAP gate do?", options: ["Copies a qubit state", "Exchanges the states of two qubits", "Resets a qubit to |0⟩"], correct: 1, explanation: "The SWAP gate exchanges the quantum states of two qubits — often needed to route information around limited connectivity." },

  // SET 3 — Hardware
  { id: 31, set: 3, question: "What temperature do superconducting qubits typically operate at?", options: ["Room temperature (25°C)", "Near absolute zero (~15 millikelvin)", "Liquid nitrogen temperature (-196°C)"], correct: 1, explanation: "Superconducting qubits require dilution refrigerators to maintain near-absolute-zero temperatures to exhibit quantum behavior." },
  { id: 32, set: 3, question: "Which company pioneered commercially accessible superconducting quantum computers?", options: ["Google", "IBM", "IonQ"], correct: 1, explanation: "IBM launched the first cloud-accessible quantum computer in 2016 and has maintained the most public-facing quantum program." },
  { id: 33, set: 3, question: "What type of qubits does IonQ use?", options: ["Superconducting qubits", "Trapped-ion qubits", "Photonic qubits"], correct: 1, explanation: "IonQ uses trapped-ion qubits — individual ions suspended by electromagnetic fields, offering high fidelity and all-to-all connectivity." },
  { id: 34, set: 3, question: "What is an advantage of trapped-ion qubits over superconducting qubits?", options: ["Faster gate speeds", "Longer coherence times and higher gate fidelity", "Lower cost to manufacture"], correct: 1, explanation: "Trapped-ion systems typically offer longer coherence times and higher gate fidelity, though at the cost of slower gate speeds." },
  { id: 35, set: 3, question: "What does Quantum Volume measure?", options: ["Number of qubits only", "A combination of qubit count, connectivity, and gate error rates", "Gate operation speed in nanoseconds"], correct: 1, explanation: "Quantum Volume (introduced by IBM) is a single benchmark number accounting for qubit count, connectivity, and error rates together." },
  { id: 36, set: 3, question: "What is qubit connectivity in a quantum processor?", options: ["The internet bandwidth of the quantum computer", "Which pairs of qubits can directly perform two-qubit gates", "The number of classical control wires"], correct: 1, explanation: "Qubit connectivity describes which qubit pairs can interact directly. Limited connectivity requires SWAP gates to route operations." },
  { id: 37, set: 3, question: "What is a dilution refrigerator?", options: ["A quantum error correction technique", "A cooling system used to reach millikelvin temperatures for superconducting qubits", "A type of qubit measurement device"], correct: 1, explanation: "Dilution refrigerators cool quantum processors to near absolute zero using helium isotope mixing." },
  { id: 38, set: 3, question: "What company uses QCCD (Quantum Charge-Coupled Device) architecture?", options: ["IBM", "Quantinuum", "Xanadu"], correct: 1, explanation: "Quantinuum's H-Series uses QCCD architecture, where trapped ions are physically shuttled between trap zones for flexible connectivity." },
  { id: 39, set: 3, question: "What type of qubits does Xanadu's Aurora system use?", options: ["Superconducting qubits", "Photonic qubits (GKP encoded)", "Neutral atom qubits"], correct: 1, explanation: "Xanadu uses photonic qubits, encoding quantum information in light. Their Aurora system demonstrated GKP logical qubits." },
  { id: 40, set: 3, question: "What is the heavy-hex lattice used by IBM?", options: ["A type of error correction code", "A qubit connectivity layout optimizing fidelity for superconducting hardware", "A classical control system architecture"], correct: 1, explanation: "IBM's heavy-hex lattice arranges qubits in a pattern minimizing crosstalk while maintaining useful connectivity for circuits." },
  { id: 41, set: 3, question: "Which processor did Google use to claim 'quantum supremacy' in 2019?", options: ["Willow", "Sycamore", "Bristlecone"], correct: 1, explanation: "Google's Sycamore processor (53 qubits) performed a random circuit sampling task claimed to take 200 seconds vs 10,000 years classically." },
  { id: 42, set: 3, question: "What significant milestone did Google's Willow processor demonstrate in 2024?", options: ["1000-qubit operation", "Below-threshold error correction scaling", "Room temperature operation"], correct: 1, explanation: "Willow demonstrated that adding more physical qubits in surface code actually decreases logical error rate — confirming below-threshold operation." },
  { id: 43, set: 3, question: "What is T2 coherence time?", options: ["Time between gate operations", "Phase coherence time — how long a qubit maintains its phase relationship", "Total computation time"], correct: 1, explanation: "T2 measures dephasing — how long before random phase noise randomizes the qubit state. T2 ≤ 2×T1 always." },
  { id: 44, set: 3, question: "What does 'all-to-all connectivity' mean in quantum hardware?", options: ["All qubits connected to classical computers", "Any qubit can directly interact with any other qubit without SWAP routing", "All gates can be applied simultaneously"], correct: 1, explanation: "All-to-all connectivity (common in trapped-ion systems) means no SWAP overhead — any pair can perform a two-qubit gate directly." },
  { id: 45, set: 3, question: "What is neutral atom quantum computing?", options: ["Using uncharged silicon atoms as classical bits", "Using individual neutral atoms held by optical tweezers as qubits", "A quantum annealing approach using neutral particles"], correct: 1, explanation: "Neutral atom systems (like Pasqal) use laser-trapped neutral atoms as qubits, offering reconfigurable connectivity patterns." },

  // SET 4 — Error Correction
  { id: 46, set: 4, question: "What is the purpose of quantum error correction?", options: ["To speed up quantum gates", "To protect quantum information from decoherence and gate errors", "To reduce the number of qubits needed"], correct: 1, explanation: "QEC encodes logical qubits across many physical qubits, allowing errors to be detected and corrected without measuring the protected information." },
  { id: 47, set: 4, question: "What is a logical qubit?", options: ["A qubit with no errors", "An error-protected qubit encoded across multiple physical qubits", "A software-simulated qubit"], correct: 1, explanation: "A logical qubit uses redundancy (many physical qubits) to behave like an ideal, error-resistant qubit despite hardware noise." },
  { id: 48, set: 4, question: "What is the surface code?", options: ["A quantum programming language", "A 2D grid quantum error-correcting code with nearest-neighbor interactions", "A classical post-processing technique"], correct: 1, explanation: "The surface code arranges qubits in a 2D grid, has a high error threshold (~1%), and requires only nearest-neighbor interactions." },
  { id: 49, set: 4, question: "What is syndrome measurement in error correction?", options: ["Measuring the logical qubit directly", "Detecting error types using ancilla qubits without collapsing the logical qubit", "Correcting gate errors by repeating operations"], correct: 1, explanation: "Syndrome measurements use ancilla qubits to reveal what error occurred without disturbing the protected quantum information." },
  { id: 50, set: 4, question: "What is the fault-tolerance threshold?", options: ["The maximum number of qubits a computer can have", "The physical error rate below which adding more qubits improves logical error rates", "The minimum circuit depth required for error correction"], correct: 1, explanation: "Below the fault-tolerance threshold, more redundancy reduces errors. Above it, adding qubits makes things worse." },
  { id: 51, set: 4, question: "Approximately how many physical qubits does one surface-code logical qubit typically require?", options: ["Exactly 5", "Hundreds to over a thousand", "Around 50"], correct: 1, explanation: "Current estimates put surface-code overhead at hundreds to over a thousand physical qubits per logical qubit at useful error rates." },
  { id: 52, set: 4, question: "What is zero-noise extrapolation (ZNE)?", options: ["A type of quantum error correction code", "An error mitigation technique that extrapolates results to a zero-noise estimate", "A hardware calibration method"], correct: 1, explanation: "ZNE runs circuits at deliberately amplified noise levels, then extrapolates backward to estimate the noiseless result." },
  { id: 53, set: 4, question: "What is the difference between a bit-flip error and a phase-flip error?", options: ["Bit-flip changes qubit energy; phase-flip changes qubit speed", "Bit-flip maps |0⟩↔|1⟩; phase-flip maps |+⟩↔|−⟩ (flips the sign of |1⟩)", "They are the same error type"], correct: 1, explanation: "Bit-flip errors are corrected by X gates; phase-flip errors are corrected by Z gates. The surface code handles both." },
  { id: 54, set: 4, question: "What gate corrects a bit-flip error?", options: ["Hadamard (H) gate", "Pauli-X gate", "Pauli-Z gate"], correct: 1, explanation: "The Pauli-X gate flips |0⟩↔|1⟩, making it the natural correction operation for bit-flip errors." },
  { id: 55, set: 4, question: "What is quantum error mitigation vs quantum error correction?", options: ["They are the same thing", "Mitigation uses classical post-processing; correction uses physical redundancy with ancilla qubits", "Correction is faster; mitigation is more accurate"], correct: 1, explanation: "Error mitigation reduces noise effects classically without qubit overhead (viable today); error correction physically eliminates errors (requires fault-tolerant hardware)." },
  { id: 56, set: 4, question: "What is a stabilizer code?", options: ["Software that stabilizes qubit coherence", "A quantum error-correcting code defined by a set of stabilizer operators", "A hardware cooling technique"], correct: 1, explanation: "Stabilizer codes (including the surface code) define protected logical states through a set of commuting Pauli operators whose eigenvalues reveal errors." },
  { id: 57, set: 4, question: "What ancilla qubits are used for in quantum error correction?", options: ["To store computation results", "To perform syndrome measurements without disturbing logical qubits", "To increase circuit speed"], correct: 1, explanation: "Ancilla (auxiliary) qubits are entangled with logical qubits, then measured to reveal error syndromes — leaving logical qubits intact." },
  { id: 58, set: 4, question: "What is the Toffoli gate?", options: ["A single-qubit phase rotation gate", "A three-qubit gate that flips the target if both control qubits are |1⟩", "A measurement basis rotation gate"], correct: 1, explanation: "The Toffoli (CCNOT) gate is a universal classical reversible gate — flipping the target qubit only when both controls are |1⟩." },
  { id: 59, set: 4, question: "Why can't quantum information be simply copied as a backup?", options: ["Quantum computers are too slow to copy", "The no-cloning theorem proves arbitrary quantum states cannot be copied", "Quantum states are too large to store"], correct: 1, explanation: "The no-cloning theorem (a consequence of quantum linearity) proves it is impossible to create an identical copy of an unknown quantum state." },
  { id: 60, set: 4, question: "What is cat qubit error correction?", options: ["An error correction approach for photonic systems using bosonic cat states", "A technique for correcting errors in room-temperature qubits", "A type of ancilla qubit preparation"], correct: 0, explanation: "Cat qubits (used by Alice & Bob) encode information in superpositions of coherent states, naturally suppressing one error type over another." },

  // SET 5 — Cryptography & Security
  { id: 61, set: 5, question: "What is post-quantum cryptography?", options: ["Encryption using quantum computers", "Classical encryption designed to resist quantum computer attacks", "Encryption that works only after quantum computers exist"], correct: 1, explanation: "PQC uses classical algorithms based on mathematical problems believed hard for quantum computers (lattice problems, hash functions, etc.)." },
  { id: 62, set: 5, question: "Which organization standardized post-quantum cryptographic algorithms in 2024?", options: ["IEEE", "NIST (National Institute of Standards and Technology)", "ISO"], correct: 1, explanation: "NIST finalized post-quantum cryptography standards in 2024, including CRYSTALS-Kyber (key encapsulation) and CRYSTALS-Dilithium (signatures)." },
  { id: 63, set: 5, question: "What is the 'harvest now, decrypt later' threat?", options: ["A classical cyber attack on quantum systems", "Adversaries collecting encrypted data today to decrypt it once quantum computers exist", "A hardware vulnerability in quantum processors"], correct: 1, explanation: "This threat motivates starting PQC migration now — data encrypted today may be decryptable in 10-20 years by future quantum computers." },
  { id: 64, set: 5, question: "What is quantum key distribution (QKD)?", options: ["Using quantum computers to generate encryption keys faster", "Using quantum mechanics to distribute encryption keys with physics-guaranteed security", "A quantum algorithm for breaking encryption"], correct: 1, explanation: "QKD uses quantum states to establish shared keys — any eavesdropping disturbs the quantum states detectably, revealing the intrusion." },
  { id: 65, set: 5, question: "Which protocol was the first quantum key distribution protocol?", options: ["E91", "BB84", "QKD-256"], correct: 1, explanation: "BB84 (1984, Bennett & Brassard) was the first QKD protocol, using polarized photons to establish shared keys." },
  { id: 66, set: 5, question: "Is AES-256 directly broken by quantum computers?", options: ["Yes, Shor's Algorithm breaks it", "No — it only faces a quadratic speedup from Grover's, addressable by doubling key length", "Yes, but only by very large quantum computers"], correct: 1, explanation: "AES is a symmetric cipher, not based on factoring. Grover's Algorithm offers only a quadratic speedup, which is countered by using AES-256 instead of AES-128." },
  { id: 67, set: 5, question: "What does E91 protocol use to establish secure keys?", options: ["Polarized photons", "Quantum entanglement and Bell inequality tests", "Lattice-based mathematics"], correct: 1, explanation: "E91 (Ekert 1991) uses entangled particle pairs and tests Bell inequalities — any eavesdropping disturbs the correlations." },
  { id: 68, set: 5, question: "What is quantum teleportation?", options: ["Physically moving matter using quantum effects", "Transferring a quantum state to a distant location using entanglement and classical communication", "Faster-than-light data transmission"], correct: 1, explanation: "Quantum teleportation transmits a quantum state using pre-shared entanglement plus two classical bits — no faster than light, no physical matter moves." },
  { id: 69, set: 5, question: "Can entanglement be used to send information faster than light?", options: ["Yes, measurement is instantaneous", "No — a classical channel is always required to interpret the correlation", "Yes, but only for small amounts of data"], correct: 1, explanation: "Measurement outcomes are random and uncontrollable — no information can be encoded. A classical channel is always needed to complete communication." },
  { id: 70, set: 5, question: "What is the no-cloning theorem's significance for quantum cryptography?", options: ["It makes quantum computers slower", "It ensures any eavesdropping on a quantum channel is detectable", "It prevents quantum computers from cracking encryption"], correct: 1, explanation: "Since quantum states can't be copied, an eavesdropper must measure (and disturb) the quantum channel to extract information — making interception detectable." },
  { id: 71, set: 5, question: "CRYSTALS-Kyber is used for which cryptographic purpose?", options: ["Digital signatures", "Key encapsulation / key exchange", "Hash functions"], correct: 1, explanation: "CRYSTALS-Kyber is NIST's standardized post-quantum key encapsulation mechanism, replacing RSA/ECC key exchange." },
  { id: 72, set: 5, question: "What mathematical problem does CRYSTALS-Kyber rely on for security?", options: ["Integer factoring", "Learning With Errors (LWE) — a lattice-based problem", "Discrete logarithm"], correct: 1, explanation: "Kyber is based on the hardness of Learning With Errors problems over lattices, believed resistant to both classical and quantum attacks." },
  { id: 73, set: 5, question: "What is quantum random number generation (QRNG)?", options: ["Generating numbers using quantum algorithms", "Using quantum measurement's inherent randomness to produce truly unpredictable numbers", "A pseudorandom number generator for quantum programs"], correct: 1, explanation: "Quantum measurement collapse is fundamentally random — unlike classical pseudorandom generators, QRNG produces true randomness." },
  { id: 74, set: 5, question: "How many classical bits does quantum teleportation require alongside entanglement?", options: ["Zero — it's purely quantum", "Two classical bits", "As many bits as the qubit state's description"], correct: 1, explanation: "Quantum teleportation requires 2 classical bits to communicate the measurement outcomes needed to complete the state transfer." },
  { id: 75, set: 5, question: "What does the Micius satellite demonstrate?", options: ["Quantum computing in orbit", "Intercontinental quantum key distribution using entangled photons", "Quantum error correction in space"], correct: 1, explanation: "China's Micius satellite (2017) demonstrated intercontinental QKD by distributing entangled photon pairs between ground stations." },

  // SET 6 — Applications & Industry
  { id: 76, set: 6, question: "Which quantum algorithm offers the most credible near-term advantage for finance?", options: ["Shor's Algorithm", "Quantum Amplitude Estimation for Monte Carlo simulation", "Grover's Algorithm for fraud detection"], correct: 1, explanation: "Quantum Amplitude Estimation provides a proven quadratic speedup for derivatives pricing and risk analysis via Monte Carlo methods." },
  { id: 77, set: 6, question: "What is quantum sensing?", options: ["Using quantum computers to process sensor data", "Using quantum phenomena to measure physical quantities with extraordinary precision", "Detecting qubits in a quantum processor"], correct: 1, explanation: "Quantum sensing uses quantum effects to measure magnetic fields, gravity, time, and other quantities with precision beyond classical limits." },
  { id: 78, set: 6, question: "What is quantum simulation used for?", options: ["Testing quantum algorithms on classical computers", "Using quantum systems to model other quantum systems (molecules, materials)", "Simulating classical programs on quantum hardware"], correct: 1, explanation: "Quantum simulation uses a controllable quantum system to model hard-to-simulate quantum systems — like molecular behavior in drug discovery." },
  { id: 79, set: 6, question: "What is quantum annealing used for?", options: ["Cooling quantum processors", "Finding approximate solutions to optimization problems", "Quantum error correction"], correct: 1, explanation: "Quantum annealing (used by D-Wave) finds low-energy states of a system, mapping optimization problems to physical energy minimization." },
  { id: 80, set: 6, question: "What industry is currently most urgently affected by quantum computing developments?", options: ["Entertainment", "Cybersecurity — due to post-quantum migration urgency", "Transportation"], correct: 1, explanation: "Cybersecurity faces the most immediate pressure from quantum computing — the 'harvest now, decrypt later' threat demands PQC migration now." },
  { id: 81, set: 6, question: "What is the realistic timeline for large-scale quantum computers breaking RSA-2048?", options: ["Already possible today", "Likely 15-30+ years, requiring millions of high-quality physical qubits", "Within 2-5 years"], correct: 1, explanation: "Breaking RSA-2048 requires millions of logical qubits with full error correction — far beyond current hardware capabilities." },
  { id: 82, set: 6, question: "What does a quantum internet require that doesn't yet exist at scale?", options: ["Faster classical networks", "Quantum repeaters to extend entanglement over long distances", "More powerful quantum computers"], correct: 1, explanation: "Quantum repeaters would extend entanglement across long distances without breaking quantum coherence — still an active research challenge." },
  { id: 83, set: 6, question: "Which sector has made the most concrete quantum computing pilots to date?", options: ["Agriculture", "Finance and pharmaceuticals", "Construction"], correct: 1, explanation: "Finance (Monte Carlo risk analysis) and pharma (molecular simulation) have the most active, credible quantum computing pilot programs." },
  { id: 84, set: 6, question: "What is the 'quantum hype cycle' problem?", options: ["Too many quantum startups competing", "A gap between inflated public expectations and actual near-term capabilities", "Excessive spending on quantum research"], correct: 1, explanation: "Like many emerging technologies, quantum computing has experienced waves of inflated expectations followed by disillusionment before realistic progress." },
  { id: 85, set: 6, question: "Can quantum computers replace classical computers for general tasks?", options: ["Yes, they are universally faster", "No — quantum computers are specialized co-processors for specific problem types", "Yes, but only for tasks requiring more than 100 qubits"], correct: 1, explanation: "Quantum computers excel at specific problem types (factoring, quantum simulation) but are impractical for general computing tasks like web browsing or word processing." },
  { id: 86, set: 6, question: "What is 'quantum advantage'?", options: ["The cost benefit of quantum computing over classical", "A demonstrated speedup of a quantum algorithm over the best known classical algorithm for the same task", "The technical advantage of using superconducting over trapped-ion qubits"], correct: 1, explanation: "Quantum advantage means a quantum computer solves a problem faster than any classical computer — a stronger claim than 'quantum supremacy'." },
  { id: 87, set: 6, question: "What is the most promising quantum computing application for climate change?", options: ["Quantum-powered electric grids", "Quantum simulation for discovering better battery materials and catalysts", "Quantum optimization of delivery routes"], correct: 1, explanation: "Quantum chemistry simulation could accelerate discovery of better battery materials and more efficient catalytic processes for carbon capture." },
  { id: 88, set: 6, question: "What does 'fault-tolerant quantum computing' mean?", options: ["Quantum computing that never makes errors", "Quantum computing reliable enough to run long computations despite physical errors, using full error correction", "Quantum computing on classical-error-corrected hardware"], correct: 1, explanation: "Fault-tolerant QC uses full error correction (logical qubits) to suppress errors to arbitrarily low levels, enabling indefinitely long computations." },
  { id: 89, set: 6, question: "Which quantum computing approach does D-Wave use?", options: ["Gate-based superconducting", "Quantum annealing", "Trapped-ion gate-based"], correct: 1, explanation: "D-Wave uses quantum annealing — a specialized optimization approach fundamentally different from gate-based quantum computing." },
  { id: 90, set: 6, question: "What is quantum machine learning?", options: ["Classical machine learning running on quantum hardware", "The study of quantum algorithms that may accelerate specific machine learning tasks", "A technique for training AI to program quantum computers"], correct: 1, explanation: "QML explores whether quantum computing can speed up certain ML tasks. Current evidence shows narrow, often impractical advantages compared to classical methods." },

  // SET 7 — Complexity & Theory
  { id: 91, set: 7, question: "What complexity class describes problems quantum computers can efficiently solve?", options: ["NP", "BQP (Bounded-error Quantum Polynomial time)", "PSPACE"], correct: 1, explanation: "BQP is the quantum analog of P — problems solvable in polynomial time on a quantum computer with high probability." },
  { id: 92, set: 7, question: "Is integer factoring believed to be NP-complete?", options: ["Yes, that's why Shor's matters", "No — factoring is in NP but not believed NP-complete", "Yes, and Shor's proves P=NP"], correct: 1, explanation: "Factoring is in NP (you can verify a factor quickly) but not believed NP-complete. Shor's Algorithm puts factoring in BQP." },
  { id: 93, set: 7, question: "What does the Bloch sphere represent?", options: ["The physical shape of a qubit", "The complete state space of a single qubit's pure states", "A diagram of quantum circuit complexity"], correct: 1, explanation: "The Bloch sphere maps all pure qubit states to points on a unit sphere. Single-qubit gates are rotations of this sphere." },
  { id: 94, set: 7, question: "What is a density matrix used for?", options: ["Measuring qubit density in a chip", "Representing mixed quantum states that include classical probability distributions", "Calculating gate fidelity"], correct: 1, explanation: "Density matrices describe mixed states — combinations of pure quantum states weighted by classical probabilities (e.g., after decoherence)." },
  { id: 95, set: 7, question: "What is a unitary matrix in the context of quantum gates?", options: ["A matrix with all entries equal to 1", "A matrix U where U†U = I, preserving quantum state normalization", "A matrix describing measurement probabilities"], correct: 1, explanation: "Unitary matrices preserve the total probability (norm) of quantum states, making them the mathematical description of quantum gates." },
  { id: 96, set: 7, question: "What is quantum supremacy?", options: ["A provable, practical speedup for a useful problem", "A demonstration that a quantum computer outperforms classical computers on a specific benchmark task", "The moment quantum computers replace all classical computers"], correct: 1, explanation: "Quantum supremacy (or quantum advantage) refers to performing a specific task faster than any classical computer — not necessarily on a practically useful problem." },
  { id: 97, set: 7, question: "What is Hamiltonian simulation?", options: ["Simulating classical Hamiltonian mechanics", "Using a quantum computer to simulate the time evolution of a quantum system under a Hamiltonian", "A classical algorithm for quantum state preparation"], correct: 1, explanation: "Hamiltonian simulation uses a quantum computer to efficiently evolve quantum systems under their governing equations — a key application for chemistry and materials." },
  { id: 98, set: 7, question: "What is quantum entanglement's role in violating Bell inequalities?", options: ["Entanglement has no role in Bell violations", "Entangled systems produce correlations that exceed what any local hidden variable theory can explain", "Bell inequalities only apply to classical systems"], correct: 1, explanation: "Bell inequality violations confirm quantum correlations cannot be explained by hidden local variables — proving entanglement is a genuine quantum phenomenon." },
  { id: 99, set: 7, question: "What is the quantum Fourier transform's primary application?", options: ["Creating random quantum states", "Encoding Fourier transform information in quantum phase — used inside Shor's and QPE", "Directly solving optimization problems"], correct: 1, explanation: "The QFT is used as a subroutine in phase estimation algorithms — its output's phases encode the Fourier-transformed information efficiently." },
  { id: 100, set: 7, question: "What is a barren plateau in variational quantum algorithms?", options: ["A quantum hardware failure mode", "A training landscape region where gradients vanish exponentially, making optimization impossible", "A type of quantum error in deep circuits"], correct: 1, explanation: "Barren plateaus cause variational circuit parameters to have exponentially small gradients as circuit depth grows, making training intractable." },
  { id: 101, set: 7, question: "What does BQP ⊆ PSPACE mean?", options: ["Quantum computers are more powerful than any classical computer", "Every problem solvable efficiently by quantum computers can also be solved (possibly slowly) by classical computers with polynomial space", "Quantum computers cannot solve PSPACE problems"], correct: 1, explanation: "This containment means quantum computation doesn't transcend classical computation completely — it operates within known classical complexity bounds." },
  { id: 102, set: 7, question: "What is a quantum walk?", options: ["A physical process in a quantum processor", "A quantum analog of classical random walks, used in search and simulation algorithms", "A debugging technique for quantum circuits"], correct: 1, explanation: "Quantum walks use superposition and interference to explore graph structures quadratically faster than classical random walks." },
  { id: 103, set: 7, question: "What is quantum channel capacity?", options: ["The bandwidth of a quantum internet connection", "The maximum rate at which quantum information can be reliably transmitted over a noisy quantum channel", "The number of gates a quantum processor can run per second"], correct: 1, explanation: "Quantum channel capacity describes the information-theoretic limit of quantum communication, analogous to Shannon capacity for classical channels." },
  { id: 104, set: 7, question: "What is an ancilla qubit?", options: ["A faulty qubit that needs replacement", "An auxiliary qubit used as a workspace for syndrome measurements or subroutine computation", "A qubit representing classical information"], correct: 1, explanation: "Ancilla qubits are helper qubits used in syndrome measurement, phase kickback, and other subroutines — typically initialized and measured during computation." },
  { id: 105, set: 7, question: "What is the phase kickback technique?", options: ["A hardware calibration method", "A technique where a controlled gate imprints a phase onto a control qubit from a target qubit's eigenvalue", "An error mitigation approach"], correct: 1, explanation: "Phase kickback is used in QPE and Shor's Algorithm — when a controlled-U gate acts on an eigenstate, the eigenvalue's phase transfers to the control register." },

  // SET 8 — Companies, People & History
  { id: 106, set: 8, question: "Who proposed the idea of quantum computers in 1981?", options: ["Peter Shor", "Richard Feynman", "David Deutsch"], correct: 1, explanation: "Richard Feynman proposed in 1981 that quantum systems should be simulated by quantum computers — one of the first formal proposals for quantum computation." },
  { id: 107, set: 8, question: "Who formally defined the quantum computer as a computational model in 1985?", options: ["Lov Grover", "David Deutsch", "John Preskill"], correct: 1, explanation: "David Deutsch formalized the quantum Turing machine in 1985, proving quantum computers are a distinct and more powerful computational model." },
  { id: 108, set: 8, question: "Who discovered Shor's Algorithm and in what year?", options: ["Lov Grover, 1996", "Peter Shor, 1994", "Charles Bennett, 1991"], correct: 1, explanation: "Peter Shor published his factoring algorithm in 1994, transforming quantum computing into a national security priority." },
  { id: 109, set: 8, question: "Who invented Grover's Algorithm?", options: ["Artur Ekert", "Lov Grover", "Alexei Kitaev"], correct: 1, explanation: "Lov Grover discovered his search algorithm in 1996, providing the first broadly applicable quantum speedup (quadratic) for unstructured problems." },
  { id: 110, set: 8, question: "What did John Bell contribute to quantum computing?", options: ["The first quantum algorithm", "Bell's theorem — proving quantum entanglement cannot be explained by hidden local variables", "The surface error correction code"], correct: 1, explanation: "John Bell's 1964 theorem established the mathematical test for ruling out hidden variable explanations of quantum correlations." },
  { id: 111, set: 8, question: "What is Alexei Kitaev known for in quantum computing?", options: ["Grover's Algorithm", "Topological quantum codes and quantum phase estimation", "The BB84 protocol"], correct: 1, explanation: "Kitaev discovered quantum phase estimation and pioneered topological quantum error correction, including the toric code." },
  { id: 112, set: 8, question: "Who coined the term 'quantum supremacy'?", options: ["Richard Feynman", "John Preskill", "Peter Shor"], correct: 1, explanation: "John Preskill coined 'quantum supremacy' in 2012 to describe the point where quantum computers outperform classical computers on any task." },
  { id: 113, set: 8, question: "What is IBM Quantum's primary programming framework called?", options: ["Cirq", "Qiskit", "PennyLane"], correct: 1, explanation: "Qiskit (Quantum Information Science Kit) is IBM's open-source Python framework for quantum programming — the most widely used framework globally." },
  { id: 114, set: 8, question: "Which company went public as the first pure-play quantum computing company in 2021?", options: ["Rigetti Computing", "IonQ", "D-Wave"], correct: 1, explanation: "IonQ listed on the NYSE in 2021 via a SPAC merger, becoming the first pure-play quantum computing company to go public." },
  { id: 115, set: 8, question: "What is Quantinuum's approach to quantum hardware?", options: ["Superconducting qubits", "Trapped-ion QCCD architecture", "Neutral atom qubits"], correct: 1, explanation: "Quantinuum (formed from Cambridge Quantum + Honeywell Quantum Solutions) uses QCCD trapped-ion hardware with industry-leading gate fidelity." },
  { id: 116, set: 8, question: "What was the National Quantum Initiative Act signed in the US?", options: ["A law banning quantum computing exports", "A 2018 law committing multi-year federal funding across NSF, NIST, DoE, and DoD for quantum research", "A certification standard for quantum computers"], correct: 1, explanation: "The NQI Act (2018) established a coordinated US quantum research program, accelerating investment and coordination across federal agencies." },
  { id: 117, set: 8, question: "Which company created PennyLane, the quantum ML framework?", options: ["IBM", "Xanadu", "Google"], correct: 1, explanation: "PennyLane was created by Xanadu, a Canadian quantum computing company specializing in photonic quantum hardware." },
  { id: 118, set: 8, question: "What is Charles Bennett known for in quantum information?", options: ["Shor's Algorithm", "Co-inventing BB84 quantum key distribution and the no-cloning theorem", "Quantum phase estimation"], correct: 1, explanation: "Charles Bennett (IBM) co-invented BB84 with Gilles Brassard in 1984 and co-proved the no-cloning theorem with Wootters." },
  { id: 119, set: 8, question: "What did William Wootters prove alongside Bennett in 1982?", options: ["The Bell inequality", "The no-cloning theorem — that arbitrary quantum states cannot be copied", "Quantum teleportation"], correct: 1, explanation: "Wootters and Bennett proved the no-cloning theorem in 1982 — a fundamental result with major implications for quantum cryptography." },
  { id: 120, set: 8, question: "What is Artur Ekert known for in quantum cryptography?", options: ["BB84 protocol", "E91 — an entanglement-based quantum key distribution protocol", "Post-quantum cryptography standards"], correct: 1, explanation: "Artur Ekert proposed E91 in 1991 — a QKD protocol using entangled particle pairs and Bell inequality tests for security verification." },

  // SET 9 — Frameworks & Programming
  { id: 121, set: 9, question: "What is the primary advantage of PennyLane over Qiskit for quantum ML?", options: ["More qubits available", "Native automatic differentiation integrating with PyTorch and TensorFlow", "Better IBM hardware access"], correct: 1, explanation: "PennyLane's automatic differentiation allows quantum circuits to be trained like neural network layers — essential for variational QML." },
  { id: 122, set: 9, question: "What does the following Qiskit code do?\n qc = QuantumCircuit(1)\n qc.h(0)", options: ["Measures qubit 0", "Applies a Hadamard gate to qubit 0, creating superposition", "Applies a NOT gate to qubit 0"], correct: 1, explanation: "QuantumCircuit(1) creates a 1-qubit circuit; qc.h(0) applies a Hadamard gate to qubit 0, producing (|0⟩+|1⟩)/√2." },
  { id: 123, set: 9, question: "What is Amazon Braket primarily used for?", options: ["Quantum algorithm development only", "Accessing multiple quantum hardware providers through a single cloud SDK", "IBM-specific quantum circuit compilation"], correct: 1, explanation: "Amazon Braket provides a unified SDK for accessing IonQ, Rigetti, Oxford Quantum Circuits, QuEra, and AWS simulators from one platform." },
  { id: 124, set: 9, question: "What language does Microsoft's Q# use?", options: ["Python only", "Q# — a domain-specific language for quantum programming with Python interop", "C++ with quantum extensions"], correct: 1, explanation: "Q# is Microsoft's quantum-specific language with a strong type system, designed for expressing fault-tolerant algorithms clearly." },
  { id: 125, set: 9, question: "What is a quantum circuit simulator?", options: ["Hardware that simulates classical computers", "Classical software that models quantum circuits by tracking state vectors or density matrices", "A visual tool for drawing circuits only"], correct: 1, explanation: "Simulators like Qiskit Aer or Cirq's simulator run quantum circuits on classical computers — essential for testing before using real hardware." },
  { id: 126, set: 9, question: "What is transpilation in quantum computing?", options: ["Translating quantum algorithms to classical code", "Compiling a quantum circuit to match a specific hardware's native gate set and connectivity", "Converting qubit measurements to classical outputs"], correct: 1, explanation: "Transpilation adapts a quantum circuit to specific hardware constraints — replacing gates with native equivalents and adding SWAP gates for connectivity." },
  { id: 127, set: 9, question: "What does 'shots' mean in quantum circuit execution?", options: ["The number of qubits in the circuit", "The number of times a circuit is executed to build measurement statistics", "The noise level of the quantum hardware"], correct: 1, explanation: "Since measurement collapses superposition to a classical bit, circuits are run many times (shots) to build a probability distribution of outcomes." },
  { id: 128, set: 9, question: "What is Cirq designed specifically for?", options: ["Quantum ML applications", "Hardware-aware NISQ circuit optimization, especially for Google hardware", "Universal quantum computing with a focus on beginners"], correct: 1, explanation: "Cirq (Google) is designed for fine-grained, hardware-aware circuit construction — optimizing circuits specifically for superconducting NISQ hardware." },
  { id: 129, set: 9, question: "What is a parameterized quantum circuit (PQC)?", options: ["A circuit with a fixed, pre-determined number of qubits", "A quantum circuit containing trainable rotation angles optimized by a classical algorithm", "A circuit that runs on parameterized (variable-qubit) hardware"], correct: 1, explanation: "PQCs are the building blocks of VQE and QAOA — quantum circuits with tunable parameters optimized by classical algorithms to minimize a cost function." },
  { id: 130, set: 9, question: "What is the purpose of qc.measure() in Qiskit?", options: ["To apply a Hadamard gate", "To measure a qubit's state and store the classical bit result", "To reset a qubit to |0⟩"], correct: 1, explanation: "qc.measure(qubit, classical_bit) collapses the qubit into a definite 0 or 1 and stores the result in the specified classical bit register." },

  // SET 10 — Global & Future
  { id: 131, set: 10, question: "Which country has announced the largest single government quantum investment?", options: ["United States", "China (~$15B estimated)", "Germany"], correct: 1, explanation: "China's estimated quantum investment (including the Hefei National Laboratory) is the largest announced by any single government." },
  { id: 132, set: 10, question: "What is the EU Quantum Flagship?", options: ["A quantum processor made in Europe", "A €1B EU-funded quantum research program (2018-2028) across computing, communication, sensing, and simulation", "A European quantum standards body"], correct: 1, explanation: "The EU Quantum Flagship funds coordinated research across member states, covering all four quantum technology pillars." },
  { id: 133, set: 10, question: "What makes silicon spin qubits potentially scalable?", options: ["They operate at room temperature", "They are compatible with existing semiconductor manufacturing processes", "They have the longest coherence times of any qubit type"], correct: 1, explanation: "Silicon spin qubits can in principle be fabricated using standard CMOS semiconductor processes — offering a path to manufacturing scale." },
  { id: 134, set: 10, question: "What is the primary quantum computing focus of Australian companies like Diraq?", options: ["Photonic quantum computing", "Silicon spin qubits compatible with standard semiconductor fabs", "Quantum annealing for optimization"], correct: 1, explanation: "Australia's quantum strategy emphasizes silicon spin qubits — a differentiated approach leveraging the country's strong semiconductor research base." },
  { id: 135, set: 10, question: "What is quantum network 'entanglement distribution'?", options: ["Broadcasting quantum programs to multiple computers", "Distributing entangled qubit pairs between distant locations for quantum communication", "Sharing quantum computation across a network"], correct: 1, explanation: "Entanglement distribution is the key resource for quantum networking — sending correlated qubit pairs to distant parties for QKD or quantum teleportation." },
  { id: 136, set: 10, question: "What is India's National Quantum Mission's target for 2031?", options: ["A 1-million qubit quantum computer", "Developing intermediate-scale quantum computers of 50-1000 qubits domestically", "Quantum supremacy demonstration"], correct: 1, explanation: "India's NQM (₹6,003 crore, 2023-2031) targets domestic development of 50-1000 qubit quantum computers and quantum communication infrastructure." },
  { id: 137, set: 10, question: "What is Japan's key quantum research institution leading domestic quantum hardware?", options: ["Fujitsu alone", "RIKEN — running Japan's first domestic superconducting quantum computer", "NTT alone"], correct: 1, explanation: "RIKEN launched Japan's first cloud-accessible domestic superconducting quantum computer (64 qubits) in 2023, partnering with Fujitsu for scale-up." },
  { id: 138, set: 10, question: "What is Pasqal's qubit technology?", options: ["Superconducting transmon qubits", "Neutral atoms arranged with optical tweezers", "Trapped calcium ion qubits"], correct: 1, explanation: "Pasqal (France) uses neutral atoms held by optical tweezer arrays — offering reconfigurable connectivity and scalable qubit placement." },
  { id: 139, set: 10, question: "What is Microsoft's differentiated approach to quantum hardware?", options: ["Superconducting qubits with better cooling", "Topological qubits based on non-Abelian anyons — higher-risk, potentially lower error rates", "Photonic qubits at room temperature"], correct: 1, explanation: "Microsoft pursues topological qubits, which theoretically have intrinsic error protection built into their physical nature." },
  { id: 140, set: 10, question: "What is the realistic near-term quantum computing timeline for practical pharmaceutical applications?", options: ["Already available today", "Plausibly within the next decade as hardware and algorithms mature", "At least 50 years away"], correct: 1, explanation: "Quantum chemistry simulation for drug discovery is considered one of the more credible near-term applications — potentially practical within 10 years for specific early-stage problems." },

  // SET 11-20 — Mixed advanced questions
  { id: 141, set: 11, question: "What is the Fredkin gate?", options: ["A two-qubit phase rotation gate", "A three-qubit controlled-SWAP gate — swaps two target qubits if the control is |1⟩", "A single-qubit measurement gate"], correct: 1, explanation: "The Fredkin (CSWAP) gate swaps two target qubits conditionally on a control qubit, and is universal for classical reversible computation." },
  { id: 142, set: 11, question: "What is quantum volume 128 (QV=128) specifically claiming?", options: ["The processor has 128 qubits", "The processor successfully runs random 7-qubit circuits with sufficient fidelity (2^7=128)", "The processor operates at 128 millikelvin"], correct: 1, explanation: "QV=128=2^7 means the system reliably handles random 7-qubit circuits — a combined measure of qubit count and quality." },
  { id: 143, set: 12, question: "What is the purpose of the Hadamard-CNOT circuit used at the start of quantum teleportation?", options: ["To measure the qubit being teleported", "To create an entangled Bell pair shared between sender and receiver", "To encode classical bits into quantum states"], correct: 1, explanation: "The H-CNOT sequence creates the pre-shared entanglement resource that makes quantum teleportation possible." },
  { id: 144, set: 12, question: "What does 'circuit depth' refer to?", options: ["The number of qubits in a circuit", "The longest sequence of gates from input to output (critical for decoherence)", "The total number of gates in a circuit"], correct: 1, explanation: "Circuit depth is the number of layers of gates — deeper circuits take longer, increasing decoherence risk on NISQ hardware." },
  { id: 145, set: 13, question: "What is the S gate's effect on a qubit?", options: ["Applies a bit flip", "Applies a π/2 phase rotation to the |1⟩ component", "Creates superposition from |0⟩"], correct: 1, explanation: "The S gate maps |1⟩ → i|1⟩ (a 90° phase rotation), leaving |0⟩ unchanged. S² = Z." },
  { id: 146, set: 13, question: "What is the T gate?", options: ["A bit-flip gate equivalent to X", "A π/4 phase rotation gate — T² = S, T⁴ = Z", "A teleportation gate"], correct: 1, explanation: "The T gate applies a π/4 (45°) phase rotation to |1⟩. Along with H and CNOT, it forms a universal gate set for quantum computing." },
  { id: 147, set: 14, question: "What is 'magic state distillation' used for?", options: ["Preparing qubits from classical bits", "Producing high-fidelity non-Clifford states (like T-gate states) needed for universal fault-tolerant computation", "A quantum annealing initialization technique"], correct: 1, explanation: "Magic state distillation takes many noisy non-Clifford states and purifies them into a few high-fidelity states — enabling universal fault-tolerant quantum computation." },
  { id: 148, set: 14, question: "What is the Clifford group in quantum computing?", options: ["A group of quantum computing companies", "The set of quantum gates that map Pauli operators to Pauli operators — efficiently simulable classically", "All gates that can be implemented without error correction"], correct: 1, explanation: "Clifford circuits (using H, S, CNOT) can be efficiently simulated classically (Gottesman-Knill theorem). Non-Clifford gates like T are needed for quantum advantage." },
  { id: 149, set: 15, question: "What is the Gottesman-Knill theorem?", options: ["All quantum circuits can be simulated classically", "Quantum circuits using only Clifford gates can be efficiently simulated on a classical computer", "Fault-tolerant circuits require exponential overhead"], correct: 1, explanation: "The Gottesman-Knill theorem shows that circuits restricted to Clifford gates can be simulated in polynomial time classically — highlighting why T gates are needed for quantum advantage." },
  { id: 150, set: 15, question: "What is the key insight behind Shor's Algorithm's exponential speedup?", options: ["It uses more qubits than classical algorithms", "It uses quantum phase estimation to find the period of a modular exponential function, from which factors are derived classically", "It applies Grover's search to find factors directly"], correct: 1, explanation: "Shor's uses QPE to find the period r of f(x)=a^x mod N in polynomial time. Period-finding reduces to factoring via classical number theory (GCD computation)." },
];

// Generate 20 exam sets by distributing questions
export function getExamSet(setNumber: number): ExamQuestion[] {
  // Each set gets questions from its designated set number
  // Sets 1-10 have 15 questions each, sets 11-20 share remaining questions
  const primary = questionPool.filter(q => q.set === setNumber);
  if (primary.length >= 20) return primary.slice(0, 20);

  // For sets without enough questions, supplement with random questions from other sets
  const others = questionPool.filter(q => q.set !== setNumber);
  const shuffled = [...others].sort(() => Math.random() - 0.5);
  return [...primary, ...shuffled].slice(0, 20);
}

// Get a random exam set (1-20)
export function getRandomExamSet(): { set: number; questions: ExamQuestion[] } {
  const setNum = Math.floor(Math.random() * 20) + 1;
  return { set: setNum, questions: getExamSet(setNum) };
}
